### ISSUE TITLE
Add integration tests for Push and Pull commands

### ISSUE THREAD

**Issue by jpreese** [open-policy-agent/conftest#129]
I would like to see us add some integration tests around our `push` and `pull` commands as both of those are sorely lacking in coverage. Based on the actions they perform, unit testing isn't going to give us as much confidence as we might like.

To tackle this, I would envision something like the following:

1. Spin up a local docker registry (maybe `docker run -it --rm -p 5000:5000 registry`)

2. Run `conftest push localhost:5000/somepolicyimage`
_(check log output, perform an http call against the registry API, some means of verifying the image was pushed)_

3. Run `conftest pull ..`
_(same as above.. check log/digest/something)_

**Comment by amitsaha** [comment]
Hi @jpreese i am keen to take a stab at this. Are there any integration tests or should they be hooked into https://github.com/open-policy-agent/conftest/blob/master/.circleci/config.yml ?

**Comment by jpreese** [comment]
Now that we support many different registry integrations, this approach changes quite differently. We'll re-evaluate if the need pops up.
