### ISSUE TITLE
Support Jsonnet input

### ISSUE THREAD

**Issue by enkov** [open-policy-agent/conftest#180]
To expand the potential places where Conftest could be used, it would be good to support [jsonnet](https://jsonnet.org) natively as an input.

**Comment by ivgenich73** [comment]
Good and useful idea! 👍🏻

**Comment by KeisukeYamashita** [comment]
@enkov  I thought you can use `conftest` to your jsonnet outout(JSON) . 
Are there problems in this solution?

**Comment by enkov** [comment]
Yes I can pipe jsonnet rendered in json, but it would be more comfortable with native jsonnet support.

**Comment by brandonkal** [comment]
Sounds like an unnecessary complexity. Why not just go the unix route?

**Comment by garethr** [comment]
@brandonkal you could argue that about all of the input types for Conftest. Jsonnet input isn't really any different to CUE or YAML in this regard. One of the purposes of Conftest is to make the user interface as simple as possible, so this isn't unnecessary complexity in my view, more one of the goals of Conftest.

**Comment by boranx** [comment]
Closing that as the support is now in the master.
