### ISSUE TITLE
Documentation for configuration file?

### ISSUE THREAD

**Issue by petemounce** [open-policy-agent/conftest#240]
I would like to see documentation around which options it's possible to place into the configuration file, along with which values are valid, and which values are defaulted.

I'd find it useful to see a safe-defaults configuration file with comments in it, somewhere.

**Comment by princespaghetti** [comment]
@jpreese I can take a pass at this. From a quick glance it seems to be expanding on the section on this page https://www.conftest.dev/sharing/ and the viper usage here: https://github.com/open-policy-agent/conftest/blob/master/internal/commands/test.go ? Should it have it's own page for configuration or would you like to keep it where it is?

**Comment by princespaghetti** [comment]
Or it could be combined with the options page if there's interest there

**Comment by jpreese** [comment]
Resolved via #354
