### ISSUE TITLE
Document the automatic finding of deny/violation rules in Rego policies by conftest

### ISSUE THREAD

**Issue by Blokje5** [open-policy-agent/conftest#259]
Conftest automatically searches Rego policies for rules that follow the format of the [denyQ regex and warnQ regex](https://github.com/instrumenta/conftest/blob/master/internal/commands/test.go#L76). We should have some documentation with examples of what rules work and get automatically picked up by conftest.

A markdown file in the docs folder can be added documenting this behaviour.

**Comment by jpreese** [comment]
The current documentation portal does highlight that Conftest only looks at `warn`, `deny, and `violation` rules. Was this issue created before that blurb was there or were you thinking of expanding upon it more?

**Comment by Blokje5** [comment]
This was indeed created before we had teh seperate documentation site. I would like to expand on that section. For example `deny_root_container` is also allowed. And that is a mechanism to seperate your rules and make an easier distinction between them in the output.

**Comment by jpreese** [comment]
This naming convention is now leveraged for `exceptions`, which is quite documented. Marking as resolved!
