### ISSUE TITLE
blocks with same name no longer testable

### ISSUE THREAD

**Issue by drewmullen** [open-policy-agent/conftest#266]
Prior to 0.17 I was able to test duplicate named blocks. For example, when you declare 2 of the same providers and alias them

**HCL2**:
```bash
$ cat main.tf
provider "aws" {
  version             = "=2.46.0"
  alias                  = "one"
}
provider "aws" {
  version             = "=2.46.0"
  alias                  = "two"
}
```

### Failing from version 0.17

**0.17 Rego**
```bash 
$ cat policy/versions_17.rego
package main

deny[msg] {
    provider := input["provider"][key]
    not provider.version

    msg := sprintf("Provider %s must have a version defined", [key])
}
```

**ERROR**:
```bash
$ conftest test main.tf -p policy/versions_17.rego -i hcl2
FAIL - main.tf - Provider aws must have a version defined
```

### Working from version 0.16:

```bash
$ /usr/local/stow/conftest_0.16.0/bin/conftest test ./main.tf -p policy/versions_16.rego -i hcl2
PASS - ./main.tf - data.main.deny
```

**0.16 Rego**
```bash
$ cat policy/versions_16.rego
package main

deny[msg] {
    some key
    provider := input[key]
    is_provider_key(key)
    not provider.version

    msg := sprintf("Provider %s must have a version defined", [key])
}

is_provider_key(k) {
	startswith(k, "provider.")
}
```

Since the rego is different to achieve the same result its possible the rego is the problem. However, I can't see that being the problem in this scenario.

**Comment by jpreese** [comment]
Does your 0.16 policy still pass if you remove a `version` from one of your providers? 

Is the expectation that if you have two providers named `aws` that they must both have a version field?

**Comment by drewmullen** [comment]
> Does your 0.16 policy still pass if you remove a version from one of your providers? Is the expectation that if you have two providers named aws that they must both have a version field?

yeah so the policy is that every provider must set a version. so if the `version` field is missing from any provider then the test fails.

**Comment by jpreese** [comment]
Adding @boranx as my initial thought is that this has to do with https://github.com/instrumenta/conftest/pull/253

But I haven't had a ton of time to really dig into this yet.

**Comment by drewmullen** [comment]
it also could be: #238 

@garethr any input?

**Comment by sarcasticadmin** [comment]
Im a colleague of @drewmullen just wanted to give my thoughts.

Currently the single provider isnt a `set` :

```
"provider": {
    "aws": { "version": "=2.46.0", "alias": "one" }
}
```

But two providers is:

```
"provider" : {
    "aws": [
        { "version": "=2.46.0", "alias": "one" },
        { "version": "=2.46.0", "alias": "two" }
    ]
}
```

It seems that `alias` is specific to the `provider` block for terraform. If a provider block is without an `alias` the provider is considered a `default` provider configuration: https://www.terraform.io/docs/configuration/providers.html#alias-multiple-provider-instances

For consistency, could we instead default to a `set` of `collections` for all `provider` blocks of the same name? This would standardize the output to:

For one provider of the same name:
```
"provider" : {
    "aws": [
        { "version" = "=2.46.0", "alias" = "one" }
    ]
}
```

For two providers of the same name:
```
"provider" : {
    "aws": [
        { "version" = "=2.46.0", "alias" = "one" },
        { "version" = "=2.46.0", "alias" = "two" }
    ]
}
```

I added some tests in #284 to cover the existing behavior.

**Comment by jpreese** [comment]
@drewmullen @sarcasticadmin 

PR to set-i-fy all blocks here. Additional discussions on the related issue.

https://github.com/tmccombs/hcl2json/pull/20

**Comment by sarcasticadmin** [comment]
@jpreese thanks for picking this back up! Ill take a look at those PR changes shortly

**Comment by jpreese** [comment]
@sarcasticadmin Awesome, much appreciated!

**Comment by jpreese** [comment]
Should be resolved now that Conftest uses the upstream hcl2json package and the changes made there have addressed this.
