### ISSUE TITLE
discussion: Change how Dockerfiles are parsed?

### ISSUE THREAD

**Issue by jpreese** [open-policy-agent/conftest#273]
I admittedly have _yet_ to do much with `Dockerfile` policies, but will most likely be starting to do soon. One thing I noticed in my initial policies was that `input` is always an array because we have `[][]Command` in our parser. Each command is also stored inside of `Cmd`.

Potential technical challenges aside, I wonder if policies written something like:

input.FROM[_].Value
input.COPY[_].Value

would be a better overall experience instead of what policies look like now:

input[i].Cmd == "some command"
input[i].Value # value of "some command"

Looking for some wise words of wisdom from those who may have written some Dockerfile policies :)

**Comment by garethr** [comment]
The reason for the top level array is that a Dockerfiles can have multiple stages. eg.

```dockerfile
FROM golang:1.7.3
WORKDIR /go/src/github.com/alexellis/href-counter/
RUN go get -d -v golang.org/x/net/html  
COPY app.go .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

FROM alpine:latest  
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=0 /go/src/github.com/alexellis/href-counter/app .
CMD ["./app"]  
```
So `input.FROM` is problematic, in that it might not be a single value, and an array means losing context of which other commands relate to that particular FROM.

The other related concern, which explains the second array, is that order matters in Dockerfile.

I'd wager there are definitely some improvements we can make here. I was expecting to do some Dockerfile policies in the not-too-distant future as well so will jot down thoughts when I do.

Similar to the Terraform parser, we shouldn't be concerned with breaking backwards compatibility in pursuit of a better output at this stage.

**Comment by ralgozino** [comment]
Hi!
One thing that could be nice is to have the actual line number on the dockerfile in order to be able to give better feedback to the user when something is not passing the checks. Right now the line number you get is the "parsed" line number, for example it doesn't take into account all the empty lines and comments

**Comment by jpreese** [comment]
Gareth's point regarding multiple `FROM` commands makes perfect sense to me, it's akin to multi-document yaml files.
