### ISSUE TITLE
Server functionality

### ISSUE THREAD

**Issue by noelo** [open-policy-agent/conftest#297]
Hi,
Any plans to add a server functionality to conftest where the tool starts up and waits for http post requests with attached files, parses and tests the files and returns the results to the caller.

**Comment by jpreese** [comment]
I personally haven't considered this. All of our use cases have been solvable by putting it on the build agent or inside of build containers. 

Is this not feasible in your situation or are you running into additional hurdles?

**Comment by noelo** [comment]
I just want to setup an endpoint so that it can be used [1] as part of a CD pipeline and also something that could be used to validate resources against as they're being developed. The users I see of this are very large orgs who's developers are pushing onto k8s clusters and the admins have no way of validating if the resources are well defined enough

**Comment by Blokje5** [comment]
If the use case is to validate workloads before they are pushed to a k8s cluster, check out [gatekeeper](https://github.com/open-policy-agent/gatekeeper). Gatekeeper is a k8s Admission Webhook that uses the open policy agent to validate workloads before they enter the cluster. You could even combine conftest and gatekeeper by applying conftest in your CI pipelines (@garethr called this shifting security left, a phrase I really like) and using Gatekeeper as well, a gatekeeper to your cluster. There is a set of policies available on [github](https://github.com/instrumenta/policies) that implement Kubesec for both Conftest and Gatekeeper and it could be a good starting point for your use case.

**Comment by garethr** [comment]
`opa` itself can be run as a daemon, and provides this sort of interface. Conftest started out as a developer-focused CLI interface.

But there are parts of Conftest (in particular the various input formats) that are useful there. Their has been some suggestions to move those into OPA for use by other tools built on-top.

@noelo It would be good to understand more specifics about your use case, and what's missing from OPA Server (https://www.openpolicyagent.org/docs/latest/#4-try-opa-run-server) in this case?

**Comment by noelo** [comment]
Thanks I'll take a look. Basically what we're looking to do is a kind of resource gate that validates resource definitions as they're being promoted into production. This would be done as a step in a CD promotion pipeline well before it got anywhere near a k8s API. 

Some existing work done here https://github.com/redhat-cop/rego-policies and https://github.com/noelo/omydb

**Comment by garethr** [comment]
@noelo sounds like you're doing this for Kubernetes?

If so I'd look at [Gatekeeper](https://github.com/open-policy-agent/gatekeeper) (another Open Policy Agent projects)  and the generic [OPA documentation](https://www.openpolicyagent.org/docs/latest/kubernetes-introduction/).

You can see one approach to building what you describe in my talk from KubeCon last year [slides](https://speakerdeck.com/garethr/applying-policy-throughout-the-application-lifecycle-with-open-policy-agent) and [video](https://www.youtube.com/watch?list=PLj6h78yzYM2NDs-iu8WU5fMxINxHXlien&v=cXfsaE6RKfc).

**Comment by jpreese** [comment]
Since alternatives exist for this situation, going to close this for the time being. Feel free to create another issue if anything suggested here does not meet all of your needs.
