### ISSUE TITLE
Sucesses output full of empty messages

### ISSUE THREAD

**Issue by tbuchier** [open-policy-agent/conftest#309]
Hello,

We have bumped our conftest from 0.15.0 to 0.18.2, and since we face a small issue on the new feature about successes output : 

We receive around 80+ lines of empty success messages, one for every deny/warn rules that passed

Our outputs look like:
```
[
	{
		"filename": "tfplan.json",
		"warnings": [
			{
				"msg": "W45 | ApiGateway stage test  should have access logging configured."
			}
		],
		"failures": [
			{
				"msg": "F001 | Invalid tags (missing minimum required tags) for the following resources: test"
			}
		],
		"successes": [
			{
				"msg": ""
			},
			{
				"msg": ""
			},
			{
				"msg": ""
			},
			{
				"msg": ""
			}
                        ...
                        ...
		]
	}
]
```

Our rules are defined in a main.rego (importing from packages) like for example: 

```
deny[msg] {
	count(rs_non_contain_minimum_tags) > 0
	msg := sprintf("F001 | Invalid tags (missing minimum required tags) for the following resources: %s", [rs_non_contain_minimum_tags[_]])
}

deny[msg] {
	count(whitelist.resource_not_whitelisted) > 0
	msg := sprintf("FG001 | AWS resource %s is not whitelisted.", [whitelist.resource_not_whitelisted[_]])
}

warn[msg] {
	count(api_gateway_stage.api_gateway_stage_acces_log) > 0
	msg := sprintf("W45 | ApiGateway stage %s  should have access logging configured.", [api_gateway_stage.api_gateway_stage_acces_log[_]])
}
```

Any idea how to solve this ?

Thanks

**Comment by jpreese** [comment]
Thanks for opening the issue, @tbuchier -- Successes have always been an interesting case because if the rule doesn't trigger the deny, we don't get the return value!

At my company, we've had great success not using an output flag, so I'd love to get some more insight on your use case, specifically: what are you using the output JSON for and what would you expect the JSON of the successes to be (e.g. same rule message as a failure, a count of successes instead, etc)?

**Comment by tbuchier** [comment]
Hello,

We are using conftest as a step in our pipelines to check the compliance of Terraform projects.
The json output is used to build a report which is later send to the teams.

So most of the time the json output isn't directly read by anyone, but when we need to debug the step or check it's log, we are left with a lot of noise 350+ lines off "nothing".

A count of success could be good, or anything else I guess.

Thanks

**Comment by jpreese** [comment]
In the next release, `conftest` will output a _count_ of successes. Resolved via https://github.com/open-policy-agent/conftest/pull/376
