### ISSUE TITLE
New Directory input, add ignore flag

### ISSUE THREAD

**Issue by 06kellyjac** [open-policy-agent/conftest#310]
The new Directory input feature is great but it'd be nice to have an ignore flag. :slightly_smiling_face:

**Comment by jpreese** [comment]
Glad you like it, @06kellyjac! Were you thinking of an ignore flag to be able to ignore file extensions?

**Comment by 06kellyjac** [comment]
more like a regex/pattern match.

for example if this is my directory structure:

```
terraform
  main.tf
  blah.tf
  modules
    some_module
      main.tf
      blah.tf
      modules
        some_sub_module
          main.tf
```

In this example a module is cloned locally & added to the repo, the main module of "some_module" is fine but "some_sub_module" doesn't meet our requirements & fails some policy checks.
So running conftest against all the tf apart from the stuff in "some_sub_module" dir would be fine. Then we can add a policy for whitelisting modules to make sure "some_sub_module" isn't used.

A current solution would either be to use `find` or something else to gather the files & feed them to `conftest` (not using the directory input feature)
Or to move the "modules" dir out of the "terraform" dir, which is possible but not necessarily ideal, especially if you want to policy test "some_module"
Or to delete the "some_sub_module" dir.

But a regex/pattern match ignore would help solve this problem & others, like ignoring `.yaml` or `Dockerfile`s etc

**Comment by jpreese** [comment]
Thanks for the clarification, the sub_module case is a really good one. Regex is probably a good place to start as it covers a lot of use cases, and if need be, we can get more granular from there.

**Comment by boranx** [comment]
Hi folks, if nobody's working on this issue, I can pick that up and prepare a PR about it.

**Comment by 06kellyjac** [comment]
I don't mind. I've got quite a few other things to work on atm :slightly_smiling_face:
