### ISSUE TITLE
Add an --admission option

### ISSUE THREAD

**Issue by moshloop** [open-policy-agent/conftest#314]
When using OPA for admission control the object being checked is wrapped in an AdmissionReview object, This issue is a feature request to automatically wrap all input objects in a mock AdmissionReview object to allow the reuse of policies between conftest and OPA admission controllers

**Comment by Blokje5** [comment]
Thanks for reporting this @moshloop. I think this is indeed a common scenario: Using conftest in CI/CD alongside an OPA Admission Controller (such as Gatekeeper). 

However I am not sure if it is something we want to solve inside of Conftest. Of course it would be nice if a user is using both Conftest and Gatekeeper, but in all other cases an `--admission` flag would just be confusing. Conftest is not focused on Kubernetes only and this flag would be only for Kubernetes.

As an alternative I think there are two approaches that could help you here:

1. There are ways to write your Rego policies to adapt to different types of input. @garethr created a policy library that checks whether the input is coming from Gatekeeper or if it is just a regular Kubernetes yaml file. You could use something similar in your policies
2. We have a (experimental) plugin system. You could create a conftest plugin that wraps kubernetes deployments in AdmissionReview objects. This can then be reused by others in the community while keeping the conftest CLI clean.

I am happy to help out getting you started with either approach. Let me know if this could work for you.

**Comment by jpreese** [comment]
@moshloop we are also actively working on a policy library to support both Conftest and Gatekeeper based policies here: https://github.com/plexsystems/konstraint/tree/main/examples/lib

Importing core and using `core.resource` in your policies will set the correct prefix.

**Comment by jpreese** [comment]
I share similar thoughts already outlined in this issue. I don't believe `conftest` itself should handle admission. Creating a gatekeeper plugin would be the better approach to solve this.
