### ISSUE TITLE
Support for rego modularity

### ISSUE THREAD

**Issue by MikaelSmith** [open-policy-agent/conftest#320]
I'd like to be able to define common modules of rego code that define helpers I want to use in multiple places. I envision this as a new CLI flag to include an additional policy files directory.

**Comment by MikaelSmith** [comment]
I've revisited this from a different angle, and have all the policies in a single directory tree with different tests (i.e., meant to run against a different set of input) segmented to different namespaces.

**Comment by jpreese** [comment]
That is typically how I approach it as well, you could use different namespaces or even just running conftest multiple times with different policy directories.

I've seen this done a lot with separating `--combine` policies from non-combined as well.
