### ISSUE TITLE
Trailing commas should not be allowed when unmarshalling JSON strings. 

### ISSUE THREAD

**Issue by aaronjheng** [open-policy-agent/conftest#323]
Per JSON spec, trailing commas is not allowed.
```
{
   "k1": "v1",
   "k2": "v2",
}
```
conftest should report such errors.

**Comment by Blokje5** [comment]
@aaronjheng Thanks for reporting this. I assume this is due to the fact that we parse JSON using a YAML parser as it is a superset of JSON. However the YAML spec does allow trailing commas. Maybe we should use a JSON parser instead so conftest errors in issues in the JSON.
