### ISSUE TITLE
Automate building Docker images on new release

### ISSUE THREAD

**Issue by garethr** [open-policy-agent/conftest#324]
Currently images are built manually (by running `make`) for each release. Ideally this should be automated as part of the build process.

**Comment by KeisukeYamashita** [comment]
How about using this CircleCI [docker orb](https://circleci.com/orbs/registry/orb/circleci/docker) to push to the registry from CircleCI?

**Comment by garethr** [comment]
@KeisukeYamashita yes, that will work. It's less an issue with how and more with time. If you want to take a run at the config then I can sort out the secrets and like on the CircleCI side.
