### ISSUE TITLE
"conftest pull" command fails to detect OCI registry GCR & ECR

### ISSUE THREAD

**Issue by KeisukeYamashita** [open-policy-agent/conftest#335]
## What

Currently, the `conftest pull` command only detects OCI registry if the passed argument contains `azurecr.io/` or `127.0.0.1:5000`. 

Therefore, if you pass GCR (or ECR) repositories, it will fail to pull. Like Azure Container Registry(ACR), we should detect GCR and ECR. 

These repository has these formats.

* GCR: `gcr.io/<PROJECT_ID>/<IMAGE_NAME>`
* ECR:  `<AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/`  (ref: [Pushing an image](https://docs.aws.amazon.com/AmazonECR/latest/userguide/docker-push-ecr-image.html))
    * `<AWS_ACCOUNT_ID>`: 12-digit number (ref: [AWS account identifiers](https://docs.aws.amazon.com/general/latest/gr/acct-identifiers.html))

And also, I think it conftest should support `localhost:5000` too.

I'd like to add these feature.

## How to reproduce

1. Push policies to GCR or Amazon ECR. Here, I pushed to GCR.

```console
$ conftest push gcr.io/<MY_PROJECT_ID>/keke-test:latest -p examples/kubernetes/policy
2020/06/29 00:53:07 pushing bundle to: gcr.io/kouzoh-p-keisuke-yamashita/keke-test:latest
...
2020/06/29 00:53:11 pushed bundle with digest: sha256:afec1c76eba2e0f9e920263dc6c4248f0cda3b6e934f692bd7cea488274a8666
```

2. Try to pull policies

It fails.

```
$ conftest pull gcr.io/<MY_PROJECT_ID>/keke-test:latest  
Error: download policies: stat /policy/gcr.io/kouzoh-p-keisuke-yamashita/keke-test:latest: no such file or directory
Usage:
  conftest pull <repository> [flags]

Flags:
  -h, --help   help for pull

Global Flags:
      --no-color        disable color when printing
  -p, --policy string   path to the Rego policy files directory. For the test command, specifying a specific .rego file is allowed. (default "policy")

```

3. Pull with `oci://` protocol added

```
$ conftest pull oci://gcr.io/<MY_PROJECT_ID>/keke-test:latest  
```

Success to pull policies. 

## Why

Because in this line here https://github.com/open-policy-agent/conftest/blob/65554401e1e879ef4b6d9776f1af7a264f27a800/downloader/detect_oci.go#L18 , conftest only detects `azurecr.io/` and `127.0.0.1:5000` as OCI Registry.

**Comment by garethr** [comment]
Thanks, merged #336 so should be fixed in the next release.
