### ISSUE TITLE
Request: Support wildcards in --namespace

### ISSUE THREAD

**Issue by garethahealy** [open-policy-agent/conftest#339]
Use case: I want multiple namespaces to be included when testing.

Currently, I can do `--namespace "main.a" --namespace "main.b"` or `--all-namespaces`. My use-case is if I have my policies structured like:
- k8s
  - k8s.containers
    - k8s.containers.limits
    - k8s.containers.security

I'd like to be able to say, run all the k8s policies, i.e.: `--namespace "k8s.*"`

It seems like it should be possible @ https://github.com/open-policy-agent/conftest/blob/master/internal/commands/test.go#L198

**Comment by boranx** [comment]
As far as I know, we have recently added that into master: https://github.com/open-policy-agent/conftest/pull/319
However, seems like what you are looking for is applying the namespaces via a Regex pattern. That could be a new feature for us to work on... 

I'm wondering folks thoughts on that, @jpreese @Blokje5

**Comment by boranx** [comment]
Also documenting `--namespace` flag would be neat.

**Comment by garethahealy** [comment]
Raised a PR, as a starter for 10.

**Comment by jpreese** [comment]
I'm not sure it's a good fit. At the moment `--namespace` is clear, you pass in a single namespace to filter on. This would turn `--namespace` into a regex, which could be a little surprising and unintuitive.

Would using `--all-namespaces` on the `k8s` dir also work for you?

```shell
$ conftest test config_file.yaml -p k8s --all-namespaces
```

**Comment by garethahealy** [comment]
@jpreese ; yes, I think that would work for me. Closing.

**Comment by garethahealy** [comment]
@boranx ; just trying to see if there's any current docs for `--namespace` - i cant find it. if there isn't, where should it be added/updated?

**Comment by garethahealy** [comment]
@jpreese ; actually, this won't work as I use the konstraint in my lib dir, which is at the root level of my policy dir.

So when I run conftest with `-p` in a child dir, i get:
`rego_type_error: undefined function data.lib.konstraint.format`

Any ideas on how I could also "import" the lib dir?

**Comment by garethahealy** [comment]
Think I've solved this with a bit of bash and regex, so I can pass multiple namespaces.

**Comment by garethahealy** [comment]
For anyone in the future that hits this problem, my bash solution:
- https://gist.github.com/garethahealy/d5ce3ff9457e3c3f1487269195bc49e5
