### ISSUE TITLE
Multiple policy directories

### ISSUE THREAD

**Issue by carlpett** [open-policy-agent/conftest#343]
I'd like to propose supporting multiple `-p` flags to the `test` command, with the effect of merging the directories as if they were one. 
Our use-case for this is allowing teams to add additional policies on top of the organisation-wide ones easily.

I do not believe there will be any new collision-management cases, but may be missing something?

As a side-note, currently giving the `-p` flag multiple times is not an error, but works as last-one-wins.

**Comment by garethr** [comment]
I think this is a good idea. +1 from me.

**Comment by Blokje5** [comment]
What if two policy directories use the same namespace. E.g. I have a policy directory A:

```
package main

deny {

}
```

and a policy directory B:

```
package main

deny {

}
```

I think it should work out fine as Deny is in this case an incrementally defined rule, but I can imagine situations where this would lead to unexpected behaviour (two rules sharing a name where one is a true/false decision, the other constructs a set). It might be good to check what happens in that case.

**Comment by carlpett** [comment]
@Blokje5 Opened a PR, see above. From my understanding, it'll be treated just the same as if both files were in the same directory, since it is complied in the same pass. So if it'd be an error to have them in the same dir, it'll still be an error.

**Comment by Blokje5** [comment]
@carlpett What I meant was that in the case of multiple policy directories because everything with the same namespace is treated as if it where in the same file, it could lead to unexpected behaviour. I don't think it is a big problem: incrementally defined rules like deny will work as expected, and other rule names are not likely to conflict. It is just something we should be aware of with multiple policy directories. e.g. what happens in the following situation:

policy directory 1
```
package main

rule_a {
  //true false rule
}
```

policy directory 2
```
package main

rule_a = object {
  // rule that defines an object
}
```

I could see a situation where additional policies added by a team clash with company wide policies and lead to unexpected compilation errors.

**Comment by carlpett** [comment]
Right, but are there cases where this would not be the expected (and desired) behaviour? With your example, isn't the compilation error a good thing?
I think adding some priority type of layer on this might make it much harder to reason about, so probably clear documentation about the implications would be my bet here.

**Comment by jpreese** [comment]
I would also think that this would be expected and desired behavior. I've had a few discussions now where individuals and teams want to keep a core set of policies, but be able to layer additional ones on top of those to allow for exceptions, different file structures, etc. 

It's just the nature of the beast when adding Rego to Rego.

**Comment by garethr** [comment]
> I would also think that this would be expected and desired behavior

Also agree.

I think explaining "this is the same behaviour if these are in the same directory" makes this easy to reason about.

**Comment by carlpett** [comment]
I've added docs for `--policy` in the PR, specifically mentioning how multiple directories interact. Let me know if it is sufficiently clear :)
