### ISSUE TITLE
Keep OPA up-to-date with latest stable version (or at least have a governance process to periodically update)

### ISSUE THREAD

**Issue by jcmcken** [open-policy-agent/conftest#348]
A few months ago someone submitted an issue (#279) asking to re-up the OPA version. 

Can we do this again? I'm missing some of the new functions like ``object.union``, etc.

Can we introduce some process by which OPA continuously gets updated on a regular cadence too?

Or is there a way I can supply my own ``opa`` binary to ``conftest``?

**Comment by garethr** [comment]
Conftest doesn't use the OPA binary, rather uses it as a library.

We've just recently formally joined the OPA project, so working in bumping the version used in Conftest on new OPA releases is definitely something we should work towards.

@tsandall @timothyhinrichs what's the best way of doing that? Even if we can open an issue on Conftest every time an OPA release is made that might be a good start. Actually bumping the dependency is pretty easy most of the time.

**Comment by tsandall** [comment]
@garethr we have a little bot that tracks OPA upstream tags and automatically opens PRs on certain repos. For example: https://github.com/open-policy-agent/opa-istio-plugin/pull/192. If you want, we can point it at conftest. We just need a Makefile target called `update-opa` that does the revendoring. Here's an example:

https://github.com/open-policy-agent/opa-istio-plugin/blob/master/Makefile#L81 - `update-opa` is called w/ TAG variable set to the new tag

https://github.com/open-policy-agent/opa-istio-plugin/blob/master/build/update-opa-version.sh - some bash executed by the target to revendor and perform any other updates (e.g., updating versions in markdown or yaml files, etc.)

**Comment by garethr** [comment]
@tsandall nice. I'll look to port the Makefile over and ping you when we're ready to get the bot pointed over.

**Comment by tsandall** [comment]
I guess another option would be a GitHub action...

**Comment by xchapter7x** [comment]
i've had a lot of success using dependabot for this https://dependabot.com/go/
Its a github marketplace integration and relatively easy to setup https://github.com/marketplace/dependabot-preview

:)

**Comment by jpreese** [comment]
This is now handled with dependabot. Dependabot handles _all_ dependencies in `go.mod`, but if we find it too noisy and want to only focus on opa, we can configure [allowed_updates](https://dependabot.com/docs/config-file/#allowed_updates).
