### ISSUE TITLE
conftest verify classes errors as success

### ISSUE THREAD

**Issue by stekershaw** [open-policy-agent/conftest#355]
When running `conftest verify`, test cases with Rego errors are marked as passed.

One way of replicating this is that I see no change in `conftest verify` output if I add a `1/0` to any Rego test case, while Opa will give an `ERROR` for that test case (`eval_builtin_error: div: divide by zero`).

I think this is due to the code checking only for failures else defaulting to success: https://github.com/open-policy-agent/conftest/blob/master/internal/runner/verify.go#L70

I will submit a pull request in the hope that will help.

**Comment by jpreese** [comment]
Resolved via #377
