### ISSUE TITLE
Add starlark support

### ISSUE THREAD

**Issue by whilp** [open-policy-agent/conftest#357]
> Starlark is a dialect of Python intended for use as a configuration language. Like Python, it is an untyped dynamic language with high-level data types, first-class functions with lexical scope, and garbage collection. Unlike CPython, independent Starlark threads execute in parallel, so Starlark workloads scale well on parallel machines. Starlark is a small and simple language with a familiar and highly readable syntax. You can use it as an expressive notation for structured data, defining functions to eliminate repetition, or you can use it to add scripting capabilities to an existing application.

The most obvious use of starlark is in bazel. There, it would be very powerful to express checks using conftest.

Fortunately, there's a good go library for reading starlark:

https://github.com/google/starlark-go

**Comment by garethr** [comment]
Definitely like this idea. Is there a good output serialization of Starlark, or at least the Bazel usage of it?
Basically if we can convert starlark to some meaningful data format then the rest is relatively easy.
