### ISSUE TITLE
[feature] add --no-fail on runs

### ISSUE THREAD

**Issue by rosscdh** [open-policy-agent/conftest#359]
Hi there,

Introducing conftest into a large multi-team environment, in order to make the uptake as gentle and non-blocking as possible, it would be grand to have a --no-fail or similar switch to not return 1 on failure and just show the report.

This will allow us to integrate into CI in a non-blocking manner and assist in uptake and better governance at a later stage.

**Comment by garethr** [comment]
Is this something that should be in the tool though? Do you have other examples of tools which take this approach?

Many CI systems support this sort of concept as part of defining steps (eg. https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontinue-on-error).

In bash you could do:

```bash
conftest test  some-file || true
```

Not wholly against this suggestion, but pointing at other examples would help I think.

**Comment by rosscdh** [comment]
yep thats fair enough..  trying to remember i think it may have been kubeval or similar... but || true will def work! silly me for not thinking of that.. thanks for the bash foo
