### ISSUE TITLE
The example security checking is incomplete 

### ISSUE THREAD

**Issue by tete17** [open-policy-agent/conftest#360]
Browsing through this repo, in the [examples](https://github.com/open-policy-agent/conftest/blob/master/examples/kubernetes/policy/deny.rego#L9), as well as as trough [here](https://github.com/instrumenta/policies/blob/master/kubernetes/security.rego#L69) I found a small issue with the way we check whether the containers ar running as `root`.

I think this validation is not sufficient. According to k8s [api](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#podsecuritycontext-v1-core) values in the SecurityContext ie: input.spec.template.spec.containers.{0-9}.securityContext takes precedence. This means this validation could pass and we could still run containers as root.

We could improve this warning by looping over all containers checking whether they have the field configured correctly. If they do then stop since the values at the pod level can't override them. If some are not set then we should also check the pod value.

Keep in mind this validation as is could lead to false positives as well as false negatives as I mentioned before.

**Comment by jpreese** [comment]
The intent for most of the examples are to just be examples as to how `conftest` can be used when writing policies (as well as provide test facets!). I don't necessarily think we should take the stance that all examples must be hardened for production.

If you're looking for a more production-ready implementation of this policy, Konstraint has one available [here](https://github.com/plexsystems/konstraint/blob/main/examples/pod-deny-without-runasnonroot/src.rego).
