### ISSUE TITLE
conftest test: successes returns msg when using --all-namespaces

### ISSUE THREAD

**Issue by phomein** [open-policy-agent/conftest#361]
Context:
- intending on using conftest on gatekeeper policies, as a sort of 'lint' step for users in our ci/cd process for helm charts before reaching the actual admissions webhook on the k8s cluster
- my directory layout is similar to the [konstraint](https://github.com/plexsystems/konstraint/tree/main/examples) examples, where I have a lib with a collection of rego packages and separate named dirs with rego policies namespaced according to the dir name
- in order to work with conftest, I'm copying lib/* and */src.rego into a tmp/policy dir 

Issue
When I run `conftest test --all-namespaces deployment_without_email.yml -o json`, I get the following output
```
[
	{
		"filename": "deployment_without_email.yml",
		"warnings": [],
		"failures": [],
		"successes": [
			{
				"msg": "data.servicelbip.violation"
			},
			{
				"msg": ""
			},
			{
				"msg": ""
			},
			{
				"msg": ""
			},
			{
				"msg": ""
			},
			{
				"msg": ""
			},
			{
				"msg": "data.emailannotation.violation"
			},
			{
				"msg": ""
			},
			{
				"msg": "data.serviceemailtag.violation"
			},
			{
				"msg": ""
			}
		]
	}
]
```

In this example, I have 3 different policy rego files in the tmp/policy dir. From what I surmise from --trace, these violations don't evaluate to true and so, shouldn't return anything. But it seems to return the first violation of each package.

As a test, I combined all 3 policy rego files into a single rego file and packaged it as main. Running `conftest test deployment_without_email.yml -o json` returns all successes without messages as expected.

My plan is to parse the output to alert users only of failures anyways, so the issue is merely cosmetic and there's the workaround of combining into a single main package, but wanted to bring this up still.

**Comment by jpreese** [comment]
Thanks for reporting this @phomein. Something definitely doesn't seem quite right.

Bare bones test case:

```rego
package main

deny {
    false
    msg = "foo"
 }
```

2. Create empty yaml file

```shell
$ conftest test empty.yaml -o json
```

```json
[
        {
                "filename": "deployment.yaml",
                "warnings": [],
                "failures": [],
                "successes": [
                        {
                                "msg": "data.main.deny"
                        }
                ]
        }
]
```

**Comment by Zelinzky** [comment]
I've been looking at this, @phomein @jpreese can you let me know the os you're using and the version of conftest you're using?
