### ISSUE TITLE
Refactor the Test command

### ISSUE THREAD

**Issue by Blokje5** [open-policy-agent/conftest#363]
Recently bugs started popping up in the `conftest test` command quite often. The logic in there has organically grown to the point where it is now hard to understand.

In essence, `conftest test` has 4 stages:
- Find configuration files & policies
- Compilation
- Query execution
- Result parsing

We could start by moving that logic into separate structs and having the `TestRunner` call those structs in order. Several of these stages could also be reused in other commands (e.g. `conftest verify` also has a compilation stage, but has a different query execution stage), however just making the `conftest test` code more maintainable will already be a big win.

**Comment by boranx** [comment]
@Blokje5 are you actually working on that or looking for someone to handle that? I'd love to review the PR if you're keen to create one

**Comment by Blokje5** [comment]
@boranx I haven't started working on it but was intending to give it a go this weekend.
