### ISSUE TITLE
Conftest for auditing sequence of objects?

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/conftest#370]
More than anything, a question / vague feature request to use as basis for discussion. It's currently difficult to use conftest (and/or OPA for that matter, but conftest is closer to this in nature) to test a list/stream of objects of unknown size and get a meaningful aggregated report back. Requirements for an aggregated report is simply 1) total number of objects tested 2) number of violations (i.e. tests failed) 3) number of passing tests / objects.

Example of this could be:
```
kubectl get deployments -o yaml | conftest test -
```
or
```
aws ecr describe-repositories | conftest test -
```
or... any arbitrary collection really where one would want to test a whole bunch of objects in sequence. Gatekeeper and the likes has this concept of auditing, and I guess that's what I'm reaching for here, but since that's scoped to kubernetes I would want a lightweight (like opa / conftest) way to run an audit of any arbitrary list of objects. What I've currently tried doing is to either 1) break out the objects and test them individually, sort of like the `kubectl conftest` plugin does.. this works in that it tests each object, but obviously fails to report any aggregate numbers as conftest is invoked on each object, or 2) run conftest with the whole list as input, with a policy (taken from the `kubectl get deployments -o yam` example) like:

```
deny[reason] {
    input.kind == "List"
    item := input.items[_]
    not item.metadata.labels.app
    reason := sprintf("%v does not have an app label", [item.metadata.name])
}
```
This comes closer to what I want as I get at least an aggregated result, but the nature of OPA's rule evaluation makes only failures count towards the aggregate:
```
305 tests, 0 passed, 0 warnings, 305 failures, 0 exceptions
```

Is there any recommended, or hacky, way to do this currently? Or would something like `conftest audit` be within the confines of the project?

**Comment by jpreese** [comment]
Thanks for raising this issue, @anderseknert! I think some form of aggregation of results could make sense.

If `conftest` is given the following input, `namespaces.yaml`:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: first-namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: second-namespace
```

You would want to know that X tests passed/failed, and **2** objects passed/failed (even though we passed in a single file). With conftest, each resource is going to be split by `---`.

In the above example with _List_, I would still consider that a single object, because at least with YAML/Conftest. If we wanted aggregation based on the _List_ type specifically, then I'd want to handle that in some other plugin.

**Comment by anderseknert** [comment]
Thanks @jpreese! The example with `List` was a little contrived, used only to show what currently takes me the closest to what I want. But ideally the policy itself should be written to test a single object. Then conftest, when run in "audit mode" would run the test for each object in the sequence and keep track of the aggregate result. So, given a policy like this, in `$(pwd)/policy`:

```rego
deny[reason] {
    input.kind == "Deployment"
    not input.metadata.labels.app
    reason := sprintf("%v does not have an app label", [input.metadata.name])
}
```
We could run:
```shell
kubectl get namespaces -o json | jq .items | conftest audit -
or
kubectl get namespaces -o yaml | yq read - items | conftest audit -
```
or, using the kubectl conftest plugin:
```shell
kubectl conftest audit deployments
```
The result would be something like:
```shell
FAIL - my-first-deployment does not have an app label
FAIL - my-other-deployment does not have an app label
FAIL - another does not have an app label
...
...
305 tests, 200 passed, 0 warnings, 105 failures, 0 exceptions
```
So when run in "audit mode", conftest would know to expect a list as the "root" element, run the policy against all items in the list, keep count of the total number of tests run, failures and successes, and report the aggregate at the end.

**Comment by jpreese** [comment]
This has been approved and merged via https://github.com/open-policy-agent/conftest/pull/376
