### ISSUE TITLE
[bug] Support for "_" in iterators

### ISSUE THREAD

**Issue by rosscdh** [open-policy-agent/conftest#386]
Hi there,

    It does not appear that conftest supports the "_" for iterators

```
not contains(input.spec.rules[_].host, "blah-plain.....com")
> Error: build compiler: compiling: 1 error occurred: policy/ingress.rego:67: rego_unsafe_var_error: var _ is unsafe
```

is this correct? Thanks! :)

**Comment by Blokje5** [comment]
Hi @rosscdh, it looks like you have a compilation error in your policy. In general there should be (almost) no differences between what OPA supports and what conftest supports.

For good resources on policy writing I can suggest the following:
- https://academy.styra.com/ is a course on Rego policies.
- The official documentation: https://www.openpolicyagent.org/docs/latest/policy-language/
- And feel free to ask in the Open Policy Agent slack: https://slack.openpolicyagent.org/

I will close this issue now.
