### ISSUE TITLE
Return exit code 2 with fail-on-warn when policies do not compile

### ISSUE THREAD

**Issue by jalseth** [open-policy-agent/conftest#387]
I would like to use the exit code from conftest to differentiate between an actual error where conftest did not run (EG: the path to the resource to test was not found), if there were any failures found, or if there were only warnings found. This necessitates three exit codes, but conftest only supports two currently.

Doing this will enable scripts that wrap conftest to use the exit code to reliably determine what the outcome of the command was and make decisions based on that.

Edit: typos

**Comment by jpreese** [comment]
I definitely agree that when the configurations can't even be evaluated due to `rego` that doesn't compile, missing files, etc the `--fail-on-warn` flag needs to return `2`. It currently returns `1`. I'm a little hesitant to add another error code to be able to distinguish between a compilation failure, and a policy failure. 

To better understand the ask, what sort of decisions are you looking to make based on a compilation failure or a policy failure?

**Comment by jalseth** [comment]
I'm wrapping conftest in a GitHub Action and if the passed in parameters are invalid and cause the compilation to fail, I want to exit early rather than attempting to parse the output and perform other actions. Currently I have to check if `stderr` starts with `Error:`.

**Comment by jpreese** [comment]
I cheated a bit and looked at the implementation 🦝 

For that case, I would just check to see if `cmd.Run()` returned an error, e.g.

```golang
func main() {
	cmd := exec.Command("conftest", "test")

	out, err := cmd.CombinedOutput()
	if err != nil {
		panic(string(out))
	}
}
```

**Comment by jpreese** [comment]
I cheated a little bit and looked at the implementation 🦝 and have a couple thoughts:

#### Using the library
In a _perfect_ world, you'd be able to use the methods that are exposed to be able to do what you're trying to do without needing the `conftest` binary.

The [loader](https://github.com/open-policy-agent/conftest/blob/master/policy/loader.go) lets you define the policies/data docs (if any)/and urls (which could be parsed before hand), and then call `.Load()` on it to create the policy engine. If a file was missing, `.Load()` would throw your error here.

You'd then call [Check()](https://github.com/open-policy-agent/conftest/blob/master/policy/engine.go#L31) to get the result itself.

#### Using the binary

If the binary is preferred, the `--out` param should let you get the `JSON` representation of the results which will pre-parse everything for you. If the Unmarshal operation fails, the policies failed for another reason, not relating to policy evaluation.

```golang
// Our bad.. these should be exposed. I'll do that now..
type jsonResult struct {
	Message  string                 `json:"msg"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	Traces   []string               `json:"traces,omitempty"`
}
type jsonCheckResult struct {
	Filename  string       `json:"filename"`
	Successes int          `json:"successes"`
	Warnings  []jsonResult `json:"warnings"`
	Failures  []jsonResult `json:"failures"`
}

func main() {
	cmd := exec.Command("conftest", "test", "-p", "thing.rego", "moo.yaml", "-o", "json")  // use json output
	out, _ := cmd.CombinedOutput()

	// If the unmarshaling failed, then conftest did not run to completion and
	// did not produce valid json so print out the error from executing the binary.
	var results []jsonCheckResult
	if err := json.Unmarshal(out, &results); err != nil {
		panic(string(out))
	}

	// results now contains .Failures .Warnings etc
	fmt.Println("results: %v", results)
}
```

**Comment by jalseth** [comment]
Thanks. I think going with the JSON structs is the best route forward for me. The primary reasons for using the binary was to keep the CI check relatively quick; if I use conftest as a library, I have to fetch all of its dependencies, build them, etc. on each CI run (likely every commit) which slows down that feedback loop.

**Comment by garethr** [comment]
I think expanding the exit codes is likely worthwhile. It's probably worth considering this more generally, ie. what would all the useful exit codes be for other types of failures?

**Comment by jpreese** [comment]
Current thoughts from previous discussions:

- Introduce a new flag, potentially `--codes`, that changes the behavior of Conftest to return a predefined set of error codes. This flag could potentially replace `--fail-on-warn`.

Example scenarios and their codes:
- 0 = success, no warnings, no failures
- 1 = at least one warning, no failures
- 2 = at least one failure
- 3 = policies failed to compile
- 4 = ...

**Comment by jalseth** [comment]
I think that makes the most sense, and it gives flexibility for future conditions as well.
