### ISSUE TITLE
Create a Windows test environment

### ISSUE THREAD

**Issue by Blokje5** [open-policy-agent/conftest#409]
If we want to support Conftest on Windows, we need to make sure that we run the acceptance tests in a Windows environment as well. E.g. #400 shows that there is a risk that certain functionality does not work on Windows.

**Comment by jpreese** [comment]
Shouldn't be too big of a hurdle. CircleCI has [matrix jobs](https://circleci.com/blog/circleci-matrix-jobs/) which would let us run CI against our current environment as well as a Windows-based one.
