### ISSUE TITLE
Push to instrumenta on release or create deprecation plan

### ISSUE THREAD

**Issue by jpreese** [open-policy-agent/conftest#419]
PR https://github.com/open-policy-agent/conftest/pull/411 updated the Circle config to push on release, but did not include the `instrumenta` project.

From @garethr's comment in https://github.com/open-policy-agent/conftest/pull/417#discussion_r495569987, an announcement should be put together stating its official deprecation.

To resolve this, the Circle config should be updated to also push to `instrumenta` _or_ formally announce that `instrumenta` is deprecated in favor of the [openpolicyagent](https://hub.docker.com/u/openpolicyagent) org (this gets my vote).

@garethr @Blokje5

**Comment by Blokje5** [comment]
I am in favor of deprecation as well. If we start sharing now that it will be deprecated, we can ensure people have time to update before the next release. 

The open question for me is what channels we should use to share. We can leave a note on conftest.dev and on the OPA slack and hopefully that is enough notice.

**Comment by jpreese** [comment]
I feel as long as the DockerHub README had a blurb about the migration (e.g. https://hub.docker.com/_/opensuse), and we made a note of it in the 0.22.0 release notes on GitHub, that would cover enough for users to be able to easily find the new image.

FWIW there doesn't appear to be a paved path for this https://github.com/docker/hub-feedback/issues/907

**Comment by Blokje5** [comment]
Updating the Dockerhub README will probably cover it. I also created #423 as I noted that the install documentation still referred to the instrumenta image. @garethr could you update the Dockerhub README of the instrumenta image?

**Comment by jpreese** [comment]
Updated our `0.22.0` release to include a note about using the openpolicyagent Docker image from DockerHub.
