### ISSUE TITLE
Documenting Push command on conftest.dev

### ISSUE THREAD

**Issue by Blokje5** [open-policy-agent/conftest#422]
The Sharing Policies section does not include documentation on the push command. We should share examples of how to use the push command as well to complete the documentation.

**Comment by jpreese** [comment]
Were there any specifics you were looking to include for the command? I am seeing a blurb about push under

_If you have a compatible OCI registry you can also push new policy bundles like so:_

**Comment by Blokje5** [comment]
Yeah just realised as well that I completely read over the documented section 🤦 . I'll close this issue.
