### ISSUE TITLE
Add option to ignore parsing errors and skip file

### ISSUE THREAD

**Issue by sudermanjr** [open-policy-agent/conftest#441]
I am trying to use conftest for testing a large number of infrastructure as code repositories, and sometimes they contain malformed files. In this case, it's actually helm charts templates that end in `.yaml` that are causing the majority of my errors.

In these cases, I would like to be able to just ignore the parsing error and skip the file. Perhaps a `--continue-on-error` flag would be sufficient?

**Comment by sudermanjr** [comment]
I just found the `--ignore` flag which has gotten me around my current issues. `--ignore .+/templates/.+\.y[a]?ml` does the trick to ignore helm chart templates entirely.

**Comment by Blokje5** [comment]
I will close this issue as the `--ignore` flag seems to solve the problem.
