### ISSUE TITLE
Support Nginx conf input

### ISSUE THREAD

**Issue by freddd** [open-policy-agent/conftest#445]
Hi,

It would be awesome to be able to create rules and test nginx configs, as far as I can tell this is not supported today. I think https://github.com/aluttik/go-crossplane could be of use. It's referred to as a go-port of https://github.com/nginxinc/crossplane).

**Comment by Blokje5** [comment]
@freddd that sounds like a really good use case for conftest. Would you like to propose a PR?

**Comment by freddd** [comment]
@Blokje5 Sure! There is only one thing that is a bit unclear to me, perhaps you could help me figure it out. When validating yaml, json and similar it's fairly easy to just match on the file extension being `.yaml` to know which parser to send it to. However with nginx configs the actual file could be called whatever really, the standard is `nginx.conf` though. Should we just assume that all `*.conf` files are nginx configs?

http://nginx.org/en/docs/beginners_guide.html#:~:text=By%20default%2C%20the%20configuration%20file,%2Flocal%2Fetc%2Fnginx%20.

**Comment by Blokje5** [comment]
Hmm good question, I think it is best in this case to use an explicit parser, don't assume anything about the `.conf` files. For example, Apache & Syslog also use the `.conf` extension, so it would be dangerous to assume the nginx format there. But conftest still supports a method in which a parser can be explicitly chosen: https://www.conftest.dev/options/#-parser.

**Comment by Blokje5** [comment]
Just updating with a discussion from Slack:

Currently the `go-crossplane` library assumes that the `nginx` conf files are passed via a file path. This does not work with `conftest` as we also support passing files via `stdin`. There is an issue for the library maintainers that can be  followed here: https://github.com/aluttik/go-crossplane/issues/9 .
