### ISSUE TITLE
Combined input leads to duplicate test outputs when input is symmetrical

### ISSUE THREAD

**Issue by Blokje5** [open-policy-agent/conftest#449]
When using combined input with symmetrical data, the policy will fail twice leading to duplicate error messages and an incorrect policy count:

```console
conftest test file1.yaml file2.yaml --combine
FAIL - Combined - main - member cannot be in more than one scrum group: two, groups: first, second
FAIL - Combined - main - member cannot be in more than one scrum group: two, groups: second, first

1 test, -1 passed, 0 warnings, 2 failures, 0 exceptions
```
In this case the policy fails twice:  once when checking file1.yaml to file2.yaml and once when comparing file2.yaml to file1.yaml. 

A gist to reproduce this issue [can be found here](https://gist.github.com/Blokje5/65806b1ce16fb1a0f2c49417074b643c).

It is an interesting issue, I am not sure whether we can solve this in conftest or whether it is only solveable by rewriting the policy. Maybe a `document` number as proposed in [#106](https://github.com/open-policy-agent/conftest/issues/106#issuecomment-550362911) could make it easier to construct policies where similar input data is combined.

**Comment by jpreese** [comment]
In hindsight I'd like to close this out and consider it something not to fix. It could be considered a bug in that the information is duplicated, but file1.yaml and file2.yaml both violate the policy. We could figure out a way to de-dupe it, but the complexity doesn't feel worth it.

The negative number of tests was a problem, but has been resolved in `v0.24.0`.
