### ISSUE TITLE
Custom-named Dockerfile can't be parsed on Conftest 0.22.0

### ISSUE THREAD

**Issue by artis3n** [open-policy-agent/conftest#451]
We have some test cases alongside our rego policies. For example, for a policy that requires all Dockerfiles to pull from our private registry, we have a "failing" test case in the directory `docker/fail_docker_not_using_registry.Dockerfile` with the content:

```dockerfile
FROM ubuntu:20.04
```

Conftest 0.21.0 can successfully parse this file and fail it as violating the policy.

In Conftest 0.22.0, we get the following error:

```
Error: running test: get configurations: get configurations: new parser: new: unknown parser: Dockerfile
```

Changing the file name to `Dockerfile` resolves the error. So, we are moving our test cases around to be `docker/fail_docker_not_using_registry/Dockerfile`.

However, Docker lets your Dockerfile be any arbitrary name, and pass it in with `-f`. Is Conftest intentionally enforcing that Dockerfiles must be called Dockerfile?

Reproduction:
- Create dockerfile named `some_name_here.Dockerfile`
- Add arbitrary dockerfile stuff, e.g. `FROM ubuntu:20.04` for a minimal valid test case
- Run `conftest -p <policies> --all-namespaces ./some_name_here.Dockerfile`
- Observe conftest 0.22.0 errors
- Rename dockerfile to `Dockerfile`
- Re-run command, observe conftest succeeds

Edit: Renaming the file `fail_docker_not_using_registry` without the `.Dockerfile` resolves the errors. So, that is easy enough for us to do. I still believe Conftest should be able to parse the file even if it has an arbitrary file extension.

**Comment by shteou** [comment]
It looks like `foo.dockerfile` works, so an issue of case sensitivity when creating a parser from the extension.
I've submitted a PR which will cater for the following:

- `Dockerfile`
- `foo.Dockerfile`
- `foo.dockerfile`

But not with arbitrary casing (e.g. `DoCkErFiLe` or `foo.DoCkErFiLe`), nor the bare `dockerfile`.

**Comment by artis3n** [comment]
My specific file uses underscores - `fail_docker_not_using_registry.Dockerfile`. Do we expect that underscores should be supported?

**Comment by artis3n** [comment]
Your PR should solve my case so I'm not worried about my previous question, 👍
