### ISSUE TITLE
Trace outputs nothing on 0.22.0 in all scenarios

### ISSUE THREAD

**Issue by artis3n** [open-policy-agent/conftest#456]
This is similar to #454 except I have not been able to run `--trace` in any situation on conftest 0.22.0. Pulling down the 0.21.0 artifact, all of my `--trace` commands work as expected. Running the same commands with conftest 0.22.0 return no stdout or stderr, although the exit code looks to still be accurate in terms of whether the tests fail or pass.

Command that works in 0.21.0, does not work in 0.22.0:

```bash
conftest test -p ./nonblocking/docker/deny_image_unless_from_artifactory/src.rego --all-namespaces --trace  __tests__/failures/docker/fail_docker_from_artifactory.dockerfile
```

Similar variations using file globs for multiple policies or multiple test files does not work in 0.22.0 but does work in 0.21.0, but that is the simplest case of one policy and one test file that fails to produce a trace in 0.22.0

![image](https://user-images.githubusercontent.com/6969296/100805555-dbf56600-33fc-11eb-8e92-3b382edf87ed.png)

**Comment by shteou** [comment]
Hey @artis3n . I'm struggling to verify this with 0.22.0 (though there's various weird flag combination behaviours I'll raise elsewhere).

I tried to reproduce with the following setup:
https://gist.github.com/shteou/12dc6f84b1c026de3e43e9604607efe3
In this case I get the trace output, although the actual pass/fail results are hidden, which doesn't seem to mirror the behaviour in the screenshot.

Could you provide some minimal policy/input files? I can try again then.

**Comment by artis3n** [comment]
Yeah - here's what I got. I get correct error codes based on whether the policy passes, but no trace output

https://gist.github.com/artis3n/43d9695f6c8cb4d263a167b68fe89328

**Comment by shteou** [comment]
Ah, excellent. I can reproduce now.
It looks like it may be somehow specific to Dockerfiles (or at least doesn't manifest itself with a yaml input). Cheers!
