### ISSUE TITLE
Feature to allow reading policies from ConstraintTemplate files

### ISSUE THREAD

**Issue by rawc0der** [open-policy-agent/conftest#474]
I would like to propose a feature for **Conftest** which allows ingestion of policy files from `ConstraintTemplate` resources.
```
conftest test --policy-from-constraint-templates <my-directory> <input-file(s)/input-folder>
```
Well maybe not exactly `--policy-from-constraint-templates`, but hear me out..
Implementing this will allow writing rego definitions that can be used Universally in both **Conftest** and **Gatekeeper** contexts. 
By using the Konstraint library you can obtain `ConstraintTemplate` resources and Conftest can be used in CI tasks for static validation, before submitting resources to the cluster. (same resources).
 
There still is another problematic aspect from Gatekeers internal design decisions of disallowing references like `data.parameters` ([discussed here](https://github.com/open-policy-agent/gatekeeper/issues/1046)) --  and as frustrating as it is you can only hack the policies once again by stripping away such definitions from the resources, before they get deployed. 🙄 .. yes, some people are actually making it work like that. 😳😳

Will this sort of feature make sense?  😁
Thanks!

**Comment by jpreese** [comment]
This does come up from time to time, and the feeling at the moment is that this would be best handled by a plugin. Would that solve your issue?

**Comment by rawc0der** [comment]
Hi @jpreese, thanks for the reply.
I definitely think a plugin is the best option of integrating features from both worlds.. (maybe more)
Conftest is a really great tool, but to use it in conjunction with Gatekeeper's Constraint resources is not that trivial. Too many different approaches for scripting around a simple scenario.

Please keep me in the loop, I'm finding some time soon to pick up development for this again!

**Comment by chr-b** [comment]
Hi @rawc0der,

I have been looking into this topic (how to use the same policies for both static analysis with conftest and runtime admission control with Gatekeeper) as well.
And from what I have seen, Konstraint seems to solve that problem. I can write the policy once and use it with both conftest and Gatekeeper after generating the constraints. That would solve my use case.
What would be the added benefit of supporting the other direction, to read constraints into conftest policies instead of generating constraint from conftest policies?

What I am missing is actually a more generic approach that allows me to generate "any" kind of policy out of a conftest policy (not just for K8s yaml files). 
E.g. use conftest policies for static analysis of Terraform execution plans. Then generate other policies from these conftest policies that can be used for runtime verification of cloud infrastructure.

**Comment by rawc0der** [comment]
Hi @chr-b,
The problem with `conftest+konstraint  policies` reading `gatekeeper resources` is that it does not allow reading parameters for policies, see [this PR](/plexsystems/konstraint/pull/91). This can be be sometimes averted if you modify underlying policies to accommodate for reading `data.parameters`. Gatekeeper uses the `Constraint` resource to enforce the policy, but also provide parameters. 
Conftest allows any generic approach to validating structured json from templated sources, assuming you write the correct rego representing your rules.

**Comment by anush-cr** [comment]
We use gatekeeper policies (without konstraint) for pod security policy enforcement and also ran into this problem when we started looking at introducing policy checks in our CI pipeline. We ended up writing a plugin (https://github.com/clover/gatekeeper-conftest) to re-write the `input` object to `input.review.object` and extract the pod template where applicable. The plugin also supports providing parameters separately. 

We keep our rego separate (to aid testing) and use helm to template the gatekeeper ConstriantTemplates and so, were able to get away without having to extract the rego from the ConstraintTemplates.

**Comment by chr-b** [comment]
Hi @anush-cr ,

Interesting. I was about to start doing something similar: extend conftest to map the input data provided with `--data` to the `input.review` space that is also used by Gatekeeper. To facilitate re-use of parameterized conftest policies.

Seems like your plugin is going into this direction. I will have a look at it.

**Comment by rawc0der** [comment]
Hi @anush-cr

Thanks for sharing the plugin, it looks promising.
Typically I am interested in Konstraint because of it’s extended type
definitions for kubernetes primitives and ability to regenerate Gatekeeper
resources from the rego files.
But definitely I will try to install the plugin and see if it fits my
use-case.

**Comment by jpreese** [comment]
I believe this is ultimately going to be out of scope for Conftest, and is a good candidate for a plugin.
