### ISSUE TITLE
Verify cannot properly deal with [msg] in deny[msg]

### ISSUE THREAD

**Issue by remcowesterhoud** [open-policy-agent/conftest#476]
**Repro:**
The policy I've got:
```
deny_apple[msg] {
    input.fruit == "Apple"
    msg := "Apple is not allowed!"
}
```
I want to create a test that guarantees Apple is getting denied. I can do that with:
```
test_deny_apple {
    deny_apple[msg] with input as {"fruit": "Apple"}
}
```
This test succeeds without problem

Now I want to create a test that guarantees Banana is not getting denied by this policy. I wrote a second test for this:
```
test_dont_deny_banana {
    not deny_apple[msg] with input as {"fruit": "Banana"}
}
```
When I try to run the tests with `conftest verify` it results in a compilation error:
`Error: running verification: load: loading policies: get compiler: 1 error occurred: policy/apple_test.rego:8: rego_unsafe_var_error: var msg is unsafe`

Once I put `not` in front of the test it suddenly can't compile anymore. If I leave `[msg]` out of the policy and the tests it works fine, however running `conftest test` will not provide an error message explaining why the policy failed so this is not a proper solution.

**Expectation**
I would expect the 2nd task to be able to compile and pass, as the policy with the given input succeeds.

**Comment by macox** [comment]
Could you try
```
test_deny_apple {
    deny_apple["Apple is not allowed!"] with input as {"fruit": "Apple"}
}
```
and
```
test_dont_deny_banana {
   deny_apple[msg] with input as {"fruit": "Banana"}
}
```

The first checks that msg is "Apple is not allowed!", i.e apple is denied. 
The second is essentially checking that msg is empty, i.e banana is not denied

**Comment by remcowesterhoud** [comment]
Unfortunately that doesn't work. The banana test for your example will fail.
```
FAIL - policy/example_test.rego -  - data.main.test_dont_deny_banana
```

**Comment by jpreese** [comment]
@remcowesterhoud if I understand the problem correctly, this is how Rego itself behaves and not a specific issue with Conftest.

When `deny_apple` is called, the result is returning (setting) the `msg` value. If `msg` gets set after the call to `deny_apply`, we know that the rule failed.

So you should be able to do something like:

```rego
deny_apple[msg] with input as {"fruit": "Banana"}
not msg
```

Alternatively, I've found keeping the top level `deny/violation` rule separate from the actual rule logic itself to be a great test enabler. This is how all of the tests are set up in [Konstraint](https://github.com/plexsystems/konstraint/tree/main/examples/container-deny-without-resource-constraints).
