### ISSUE TITLE
Dockerfile - add multistage support

### ISSUE THREAD

**Issue by gecube** [open-policy-agent/conftest#477]
Hello!

It looks like that the support of multistage Dockerfile's in conftest is absent. What do I mean?

For example, let's take the next Dockerfile:

```
FROM ubuntu:latest as builder
RUN export node_version="0.10" \
&& sudo apt-get update && apt-get -y install nodejs="$node_verion"
RUN apt-get upgrade
COPY package.json usr/src/app
RUN cd /usr/src/app \
&& npm install node-static

USER root

EXPOSE 80000
WORKDIR /ololo

USER root

CMD ["npm", "start"]
```

It will be parsed as 

```
[
	[
		{
			"Cmd": "from",
			"Flags": [],
			"JSON": false,
			"SubCmd": "",
			"Value": [
				"ubuntu:latest",
				"as",
				"builder"
			]
		},
...
```

If there is multiple FROM directive in the source Dockerfile, there is no way to detect to what FROM the next instructions belong. Or I found the necessity to build the rule which will evaluate the last FROM against some expression - it is difficult to build short and nice rule for it.
What would I like to see?
A separate entry in JSON called `stage` of integer type and incremented in every next FROM block. So the basic 1-stage Dockerfile will look like:

```
[
	[
		{
			"Cmd": "from",
			"Flags": [],
			"JSON": false,
			"SubCmd": "",
			"Value": [
				"ubuntu:latest",
				"as",
				"builder"
			],
                         "Stage": 0  <------
		},
...
```

It will allow to build nice and clean rules referring to contents of the particular stage or, for instance, referring the last stage of multistage Dockerfile

**Comment by macox** [comment]
Incase it helps, you could use some something like:
```
fromCmds = froms {
	froms = [cmd | cmd = input[i]; input[i].Cmd == "from"]
}
```
To gather all the froms in to an array. A count on this would when give you the last stage

**Comment by gecube** [comment]
@macox thanks, I used the same approach :-) But it is not scalable to other instruction (i.e. to understand that particular instruction XXX belongs to stage YYY)
