### ISSUE TITLE
Count skipped tests with "conftest verify"

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/conftest#479]
With the next release of OPA tests comes the option to skip tests by prefixing them `todo_test_`. We should include handling of that in conftest too. I was going to submit a PR but realized it's not an easy thing to depend on an unreleased version, so just adding this issue in the meantime as a reminder :)

**Comment by jpreese** [comment]
> With the next release of OPA tests comes the option to skip tests by prefixing them `todo_test_`. We should include handling of that in conftest too. I was going to submit a PR but realized it's not an easy thing to depend on an unreleased version, so just adding this issue in the meantime as a reminder :)

I just bumped the opa dependency to `0.27.1`. Since we just use the test runner provided by OPA, we should just get this for free with the import.

As a sanity check I did try `conftest verify` against a set of policies and policy tests with and without `todo_` and the test count does go down when adding `todo_`

**Comment by anderseknert** [comment]
Nice! Yeah only thing needed should be to add this to the various reporter formats then. I can work on that this week unless someone beats me to it :)

**Comment by jpreese** [comment]
@anderseknert I'm eyeballing a `v0.24.0` release sometime in the near future* Just giving a heads up in case you want to tackle this before then. I can take a look as well if you're bogged down with other shenanigans, just let me know!

*near future subject to be any date.. really..*

**Comment by anderseknert** [comment]
Oh! I have indeed been busy with other commitments, but I'd like to try and tackle this tonight. If I don't make it I'll let you know so that you may take over. Thanks for the heads up!

**Comment by anderseknert** [comment]
Finally got around to it @jpreese :) Thanks for the reminder!
