### ISSUE TITLE
support scanning Dockerfiles with extensions in name?

### ISSUE THREAD

**Issue by nhung617** [open-policy-agent/conftest#491]
Hello,

Would it be possible to have Conftest ignore extensions in Dockerfile names? 

I have a Dockerfile called `Dockerfile.vouch` that triggered the following error with Conftest 0.22.0:
`Error: running test: get configurations: get configurations: new parser: new: unknown parser: vouch`

Unfortunately I'm running Conftest on files from multiple teams in my org so it may not be feasible to ask everyone to change their Dockerfile names 😆.

**Comment by garethr** [comment]
You can force the parser explicitly with `--parser dockerfile` https://www.conftest.dev/options/#-parser

We could also consider setting the parser automatically for `Dockerfile.*` as well https://github.com/open-policy-agent/conftest/blob/master/parser/parser.go#L96-L98.

**Comment by jpreese** [comment]
I think checking for both cases makes sense to do, opened #492 for this.

**Comment by nhung617** [comment]
awesome, thanks for the suggestion @garethahealy and the PR @jpreese! I really appreciate the quick response.

**Comment by artis3n** [comment]
Thanks, both! @garethr , in this case we are running Conftest against several file formats in the same repo (dockerfile, yaml, hcl, etc.) so we can't specify a specific parser. Although for general use, that would be a fix.

**Comment by jpreese** [comment]
To be resolved in `0.24.0`
