### ISSUE TITLE
feat: Parse image parts from Dockerfile 

### ISSUE THREAD

**Issue by lukasmrtvy** [open-policy-agent/conftest#500]
Would be nice to be able to parse and reference image parts from Dockerfile.

Something like: `[registry_hostname[:port]/][user_name/](repository_name[:version_tag])`

Thanks

**Comment by jpreese** [comment]
@lukasmrtvy do you have more information about your use case? I don't quite follow what you're trying to accomplish

**Comment by jalseth** [comment]
Hi @lukasmrtvy. The following Rego will pull all images from the Dockerfile input, and you can then normalize them and make other policy decisions that way.

```rego
# Returns all base images in the Dockerfile
base_images[img] {
    cmd := input[_]
    cmd.Cmd == "from"
    is_base_img(cmd.Value)
    img = cmd.Value[0]
}

is_base_img(img_values) {
    count(img_values) == 1
}

is_base_img(img_values) {
    count(img_values) == 3
    not non_base_images[img_values[0]]
}

# Parses `FROM xyz as abc` so the nicknames for different stages can be ignored 
non_base_images[img] {
    cmd := input[_]
    cmd.Cmd == "from"
    count(cmd.Value) == 3
    img = cmd.Value[2]
}
```

Using the [`conftest` Dockerfile](https://github.com/open-policy-agent/conftest/blob/51320a050658bc5703477931f308fd493a6fcea0/Dockerfile) as an example and throwing a violation for everything returned by `base_images`, you can see we extracted only the base images from the config:
```
./conftest test -p dockertest.rego Dockerfile --all-namespaces
FAIL - Dockerfile - dockertest - golang:1.16.6-alpine
FAIL - Dockerfile - dockertest - alpine:3.14.0

2 tests, 0 passed, 0 warnings, 2 failures, 0 exceptions
```

Let me know if this works for you.

**Comment by jalseth** [comment]
@lukasmrtvy Since I haven't heard from you in some time and this can be implemented in the Rego, I'm going to close this. Feel free to reopen it or open a new issue if you have any other questions.
