### ISSUE TITLE
Consider .yamllint file extension => yaml

### ISSUE THREAD

**Issue by artis3n** [open-policy-agent/conftest#504]
I ran `conftest` on a repo containing a `.yamllint` file and received the error: `running test: get configurations: get parser: unknown filetype given: yamllint`. Which makes sense, and I didn't have any policies that are looking for yamllint rules.

However, the format of the file is regular YAML, so conftest _should_ parse it correctly and not throw an error.

**Comment by jpreese** [comment]
Thanks for reporting this @artis3n!

What command are you running to get this error? Conftest should just ignore any filetype it does not recognize. Alternatively you can force a parser with `--parser yaml`

**Comment by artis3n** [comment]
Hm, didn't realize conftest is supposed to ignore files with odd extensions.

I am running conftest in an AWS Lambda function after collecting a subset of files from a git repo. Collecting any files matching file extensions I want to care about (namely, .yml, .yaml, .tf, Dockerfile, etc. along the same vein).

I'm picking up `.yamllint` as it matches `.yaml`. Notably, I also saw issues with `.yml.j2` files resulting in the same error for `unknown filetype given: j2`. I chalked that up to my matching patterns being off, but let me know if conftest should still ignore incompatible files when used in this way:

After collecting the subset of files I want to scan, I run conftest with this command:

```bash
conftest test -p /directory/holding/policies --all-namespaces -o json /absolute/path/to/file /absolute/path/to/file2 ...
```

Where each discovered filepath is included.

**Comment by jpreese** [comment]
Oh, I see. This would be expected. The skipping files behavior is for directories. 

If you pass in a specific file (e.g. /absolute/path/to/myfile.yamllint) it will error because you're giving it a specific file to use. You would have to do `conftest test /abs/path/to/myfile.yamllint --parser yaml`

That said if all of your files are expected to be yaml, just passing `--parser yaml` should work for you.

**Comment by artis3n** [comment]
What are your thoughts on adding `.yamllint` as a parseable option in conftest? I can't really think of a rego policy I'd want to write on that as a linter config file, but it is standard yaml so the AST is already there 🤷‍♂️

**Comment by jpreese** [comment]
The downside becomes that conftest will then load in more files than it needs to, and potentially throw policy errors for files that users didnt want to actually check. i.e. if a .yamllint config file somehow caused a policy violation with the loaded rules -- users would then have to exclude it (problem here is we're trying to include it)

If you're saying that you werent even trying to run policy checks against yamllint -- I'd lean in favor of just not passing it in.

**Comment by artis3n** [comment]
Makes sense to me!
