### ISSUE TITLE
conftest push to OCI doesn't work

### ISSUE THREAD

**Issue by camaeel** [open-policy-agent/conftest#505]
In file /tmp/1/policy/1.rego I created simple policy:
```
package main
deny {
  input.kind == "Deployment"
}
```

Now when I try to run `conftest push oci://example.com/asdadasd:latest` in `/tmp/1` it tries to send http request to https://oci/... . This doesn't work with any domain I tried.

```
2021/03/16 08:39:51 pushing bundle to: oci://example.com/asdadasd:latest
WARN[0000] reference for unknown type: application/vnd.cncf.openpolicyagent.policy.layer.v1+rego  digest="sha256:758a1362c12d94841bcce53a2ab30120d3880e1bd473b27100ef810e35597aa3" mediatype=application/vnd.cncf.openpolicyagent.policy.layer.v1+rego size=61
WARN[0000] reference for unknown type: application/vnd.cncf.openpolicyagent.config.v1+json  digest="sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a" mediatype=application/vnd.cncf.openpolicyagent.config.v1+json size=2
Error: push bundle: pushing manifest: failed to do request: Head https://oci/v2/example.com/asdadasd/blobs/sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a: dial tcp: lookup oci on 100.64.0.1:53: no such host
```

**Comment by jdolitsky** [comment]
@camaeel - please try dropping the `oci://` prefix: https://www.conftest.dev/sharing/

**Comment by Blokje5** [comment]
Yeah @jdolitsky is right. We at the moment only support pushing to OCI registries, hence no need to add a prefix. But for pulling policies we support HTTP/Git/OCI/etc. so we need the prefix to separate between the different mechanisms

**Comment by jdolitsky** [comment]
@Blokje5 - this the 2nd time ive seen somebody run into this. If OCI is the only transport right now, maybe make sense to trim prefix `oci://`?

**Comment by jpreese** [comment]
> @Blokje5 - this the 2nd time ive seen somebody run into this. If OCI is the only transport right now, maybe make sense to trim prefix `oci://`?

Makes sense to me

**Comment by jdolitsky** [comment]
I dont have much of an opinion on this @jpreese . In some cases, oras library consumers may wish to make the underlying distribution mechanism (OCI) opaque to the user

**Comment by jpreese** [comment]
For the time being I don't think it hurts anything to strip it on the Conftest side of things. Just wanted to double check if this is something that could be fixed purley within the ORAS code base by allowing the `oci://` prefix.

**Comment by jpreese** [comment]
@camaeel @jdolitsky this should be resolved via https://github.com/open-policy-agent/conftest/pull/521
