### ISSUE TITLE
Parse .tfvars files as HCL

### ISSUE THREAD

**Issue by artis3n** [open-policy-agent/conftest#511]
Conftest doesn't like the `.tfvars` file extension. It would be helpful to be able to write policies against org-wide standards on infrastructure as code as they would relate to variables. Could we include `.tfvars` as valid HCL?

Going to look into the [pre-processor plugin](https://github.com/open-policy-agent/conftest/issues/226) support to generate a plan to scan which was on my plate anyway, but it is helpful for some policies to evaluate on the raw HCL source files.

**Comment by jpreese** [comment]
I don't see why we couldn't include `.tfvars` as a valid file extension. If the `.tfvars` file is just HCL couldn't we just add it to the extensions list? https://github.com/open-policy-agent/conftest/blob/master/parser/parser.go#L64

**Comment by artis3n** [comment]
I need to get more familiar with how this project's code is structured so I can more effectively contribute. I don't see where file extensions are defined around the code you linked, however.

**Comment by artis3n** [comment]
Never mind, I see it :)
