### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by MFAshby** [open-policy-agent/conftest#516]
Hi!

I'm attempting to run [garden](garden.io) on my low-power ARM64 based laptop. That software depends on conftest, and unfortunately there are no arm64 builds of conftest available to download!

Since conftest is written in go, it should be relatively simple to cross-compile. See other projects for inspiration e.g. [faas-cli](https://github.com/openfaas/faas-cli/)

**Comment by jpreese** [comment]
@MFAshby we do release a few ARM64 options which can be seen under the `assets` section here: https://github.com/open-policy-agent/conftest/releases/tag/v0.23.0

Is there a particular OS/ARCH that you're looking for?

**Comment by MFAshby** [comment]
Arm64 Linux was exactly what I was after. I have no idea how I missed it's presence in the download list there. Sorry for the noise
