### ISSUE TITLE
docs: conftest verify not mentioned in docs

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/conftest#524]
The docs should provide a short description of `conftest verify` and ideally a few examples.

**Comment by DBX12** [comment]
I second that. While `conftest verify --help` tells you to read about rego tests [here](https://www.openpolicyagent.org/docs/latest/policy-testing/), you get little information on how to run it correctly.
It seems like the `--policy` parameter is mandatory (as in `conftest test`). For me worked
```
conftest verify --policy /path/to/policy/dir
```
