### ISSUE TITLE
docs: `--combine` option example produces Rego compile error

### ISSUE THREAD

**Issue by 44smkn** [open-policy-agent/conftest#550]
#### What happened:

When running the below command in the `--combine` option example, the following error is produced.

https://github.com/open-policy-agent/conftest/blob/5cd81f40d1f4f3644fd5ebc56a593c284082e9d1/docs/options.md#--combine

``` 
$ conftest test manifests.yaml --combine
```

```
Error: running test: load: loading policies: get compiler: 1 error occurred: policy/combine.rego:5: rego_compile_error: var deployment referenced above
```

#### Environment:

```sh
$ conftest -v 
Version: 0.24.0
```

**Comment by jpreese** [comment]
Thanks for reporting this, @44smkn! I've opened a PR to update the example in the documentation.
