### ISSUE TITLE
Add support to silence exceptions in `conftest test` output

### ISSUE THREAD

**Issue by iffyio** [open-policy-agent/conftest#568]
Currently conftest logs exceptions to stdout in addition to warnings and errors. This is problematic in a large code base running against lot of files with exceptions - it becomes harder to visually see the one warning or error that triggered a failure in the midst of hundreds of exceptions.
It would be really helpful if conftest say, included a flag to not log exceptions

**Comment by jpreese** [comment]
Seems like a reasonable feature.
