### ISSUE TITLE
Add informative traces for conftest verify for better debugging experience

### ISSUE THREAD

**Issue by lanasalameh1** [open-policy-agent/conftest#576]
running 'conftest verify --trace' simply prints all rego queries output. this leads to a very bad debugging experience when having a lot of tests.

"opa test -v" returns a nit output including traces of rego queries output filtered on failures only, in addition to summary report with failed , skipped and succeeded tests (in conftest verify there is no summary when --trace is on for example).
(see differences in attachments)

[
<img width="1597" alt="conftest_verify" src="https://user-images.githubusercontent.com/84773754/120499300-9d029600-c3c8-11eb-8277-a82023b2f498.png">
<img width="1177" alt="opa_test" src="https://user-images.githubusercontent.com/84773754/120499308-9e33c300-c3c8-11eb-98e7-3d0860013f64.png">

](url)

**Comment by jalseth** [comment]
This was implemented in 578, closing.
