### ISSUE TITLE
Functions without input parameters are considered undefined

### ISSUE THREAD

**Issue by artis3n** [open-policy-agent/conftest#590]
Was struggling with this for a bit. Having defined a function:

```rego
test_function() output = {
    output := "result"
}
```

and trying to invoke it via this rule:

```rego
violation[{"result": result}] {
    result := test_function()
}
```

I received an error:

```
rego_type_error: undefined function [...] test_function
```

However, after adding an arbitrary input parameter, the function is fine and the policy evaluates:

```rego
test_function(not_used) output = {
    output := "result"
}

violation[{"result": result}] {
    result := test_function("")
}
```

I don't see this [documented](https://www.openpolicyagent.org/docs/latest/policy-language/#functions) and it seems like incorrect behavior. Let me define a function without input params! :smile:

**Comment by jalseth** [comment]
Hi @artis3n. In Rego that would not be called a function as it takes no parameters, so no parenthesis are needed. The following will work:

```rego
package play

test_function = output {
    output := "result"
}

violation[{"result": result}] {
    result := test_function
}
```

This is touched on briefly [here](https://www.openpolicyagent.org/docs/latest/policy-language/#the-basics) in the comparison of `v`. I agree the documentation could be made a little more clear. If you have ideas on how to do that, we'd welcome a PR in the OPA repo to update the documentation.

Also, in the future, any issues you think exist in the Rego language should be filed under the upstream OPA project https://github.com/open-policy-agent/opa as conftest is a consumer of that for everything Rego related.

**Comment by artis3n** [comment]
Thanks for that clarification! I feel dumb.

Also forgot whose documentation I was looking at. OPA project for Rego issues makes sense.
