### ISSUE TITLE
Help?.. How do I specify a branch with conftest pull git://https.....

### ISSUE THREAD

**Issue by pingcrosby** [open-policy-agent/conftest#611]
Please can you help..

I am struggling to specify a branch when using 
```conftest pull "git::https://myuser:mytoken@mygitlabrepos"```

Can you tell me how to specify a branch here eg

```conftest pull "git::https://myuser:mytoken@mygitlabrepos?branch=XXX"``` etc etc

**Comment by jalseth** [comment]
Hi @pingcrosby. Conftest uses the `go-getter` library under the hood which supports specifying a Git reference such as a branch name. You'll want to check out their docs for more info: https://github.com/hashicorp/go-getter#git-git. Let me know if there's anything else I can help answer.

**Comment by pingcrosby** [comment]
Thanks adding "?ref=branchname" at the end solved it
