### ISSUE TITLE
conftest running time

### ISSUE THREAD

**Issue by gferr** [open-policy-agent/conftest#626]
We've been using `conftest test` in our CI server with an increasing dataset (~4K files as of now).
We've noted a considerable difference in time when this command is executed with the whole dataset or with chunks of it.

For example, running this command inside a Docker with 1000 files, I've got `3:46.55` total time.
While considering the same dataset but now breaking it into chunks of 100 files and executing the command 10 times, I've got `1:53.82` total time.

Is there any reason for that? Currently, we use `combine= true` will we lose any validation feature by doing that?

**Comment by jalseth** [comment]
Hi @gferr thank you for opening the isssue. This isn't something I've personally experienced, but is definitely an issue. I have a few follow-up questions regarding this:

- Does it also happen if not running in Docker?
- What types of files are being tested?
- Are all resources to be tested local or are they remote via NFS or similar?

**Comment by jpreese** [comment]
@gferr is this still a problem for you? If so, providing the answers to @jalseth's question could help us dig a bit more. Thanks!

**Comment by jpreese** [comment]
Closing as stale. Please do not hesitate to reopen if this is still problematic
