### ISSUE TITLE
[Brew] Calling bottle :unneeded is deprecated

### ISSUE THREAD

**Issue by gofort** [open-policy-agent/conftest#632]
Every time `brew upgrade` command output looks like this:
```
$ brew upgrade
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the instrumenta/instrumenta tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/instrumenta/homebrew-instrumenta/Formula/conftest.rb:9
```

**Comment by jalseth** [comment]
I don't have access to a Mac at the moment. @jpreese can you take a look at this one?

**Comment by princespaghetti** [comment]
I ran into this as well. It's due to the homebrew config in the instrumenta org before conftest got moved over to open-policy-agent (and tap to the main homebrew repo). 

so if you do the following should be back in business 
```
brew remove conftest
brew untap instrumenta/instrumenta
brew install conftest
```

**Comment by jpreese** [comment]
Agree with @princespaghetti -- I think I recall having to do this when the migration was first done. Closing for now, but if this does not resolve your issue please do not hesitate to re-open.
