### ISSUE TITLE
Unable to use contest for scanning using container

### ISSUE THREAD

**Issue by sudhirkumar05** [open-policy-agent/conftest#644]
I would like to scan our terraform code using conftest policy using docker container but it fails. Below are sample.
`test_plan.json` is the terraform plan json file, present in the project  root directory.
` docker run --rm -i --pull=always openpolicyagent/conftest:v0.28.3 test ./test_policy.json`

`Error: running test: parse files: get file info: stat ./test_policy.json: no such file or directory`

`< ./test_plan.json docker run --rm -i --pull=always openpolicyagent/conftest:v0.28.3 test -p ./policy`
Here, `./policy` is present in project root directory
it gives `Error: missing required arguments`

**Comment by jpreese** [comment]
In your first example, `test_plan.json` doesn't look to be added into the container.

In your second example, it looks like you are not giving `test_plan.json` as a parameter. The command is just `test -p ./policy`

**Comment by sudhirkumar05** [comment]
You are right, this should be mounted to the container to use it.
` docker run -v $(pwd):/tmp --rm -i --pull=always 'openpolicyagent/conftest:v0.28.3' test /tmp/test_plan.json -p /tmp/policy/`
