### ISSUE TITLE
Support for filename and filepath of the config in input data

### ISSUE THREAD

**Issue by sujeeth-alef** [open-policy-agent/conftest#65]
I would like to test if the namespace of the resource is the same as folder name where my configuration files are present. In this case, I would like to get the parent folder name.

**Comment by garethr** [comment]
Thinking about this, I wonder if one approach is to add this into `data.conftest`? This could be used to inject other external data. Their is a risk using this of writing tightly coupled tests that aren't portable, but there are config formats where the names are meaningful in some way.

**Comment by rydrman** [comment]
I have this exact use case as well of ensuring that the folder name always matches the namespace - in our git-ops workflow the structure of the repository is important to structure of the controlled cluster and something like `data.conftest` sounds like a perfect solution

**Comment by jpreese** [comment]
@rydrman @garethr there have been ongoing discussions related to multi-document configurations (configuration files that contain more than one configuration). A proposal is to add a `.path` and a `.contents` field to the `input` when in `--combined` mode. Original issue: https://github.com/open-policy-agent/conftest/issues/106  // PR: https://github.com/open-policy-agent/conftest/pull/388

While this would only be useful when using `--combine`, even on a single document, its another option to get the originating path of the input.

**Comment by jpreese** [comment]
I've run into this a few time myself and feel it would be a good addition. We already have all of the file names and their paths when we search for files to run tests against. I'll see if I can put something together.

**Comment by jalseth** [comment]
Added in #610 and it will be included in the next release.
