### ISSUE TITLE
It's there a expected date for compatibility with last OTA release 0.36?

### ISSUE THREAD

**Issue by slargo** [open-policy-agent/conftest#658]
Hello there, 

Looking at the last release notes, I found there is a very usefull net built-in function in this version (net.lookup_ip_addr(name)). So i was wondering when it be available for use with Conftest. 

Regards,

**Comment by jpreese** [comment]
Our dependabot integration seems to have stopped picking up OPA updates. We'll look into why and cut a new release of Conftest sometime early next week with the latest OPA library.

**Comment by jpreese** [comment]
To be resolved in https://github.com/open-policy-agent/conftest/pull/659
