### ISSUE TITLE
Can conftest perform partial matching of strings in SPDX documents? 

### ISSUE THREAD

**Issue by rnjudge** [open-policy-agent/conftest#669]
`./conftest test --policy policydir doc.spdx` takes an SPDX document, `doc.spdx`, and pass/fails the document against a set of rules defined in  `policydir/spdx.rego`.  An example set of rules is:
```
deny[msg] {
    input.CreationInfo.DataLicense != "CC0-1.0"
    msg = sprintf("DataLicense must be CC1.0 in : %v”, [input.CreationInfo.DataLicense])
}

# Explicitly deny a package named “busybox”
deny[msg] {
    input.Packages[i].PackageName == "busybox"
    msg = sprintf("Package not allowed: %s", [input.Packages[i].PackageName])
} 
```

The rules in the example field above all utilize direct compare string values. 

Is it possible to perform partial matching of strings for pass/fail validation here? For example, if I wanted to fail the SPDX document if the string `GPL` or `gpl` existed in a large block of copyright text, could I do that (and how)? Pointers or example code would be much appreciated :)

Thanks!

**Comment by jalseth** [comment]
Hi @rnjudge ! You can use the `contains(string, search)` builtin [1]. Keep in mind that conftest uses OPA for policy evaluation, so the OPA docs are a good source of information for inquiries like this.

[1] https://www.openpolicyagent.org/docs/latest/policy-reference/#strings

**Comment by jalseth** [comment]
Since I haven't heard back in a couple weeks, I'm going to close this. Feel free to reopen if you have any further questions!
