### ISSUE TITLE
CLI -v (version) flag should also output OPA/rego version (or it should be displayed somewhere)

### ISSUE THREAD

**Issue by jcmcken** [open-policy-agent/conftest#671]
It's useful for policy developers to understand what Rego built-in functions or other language features are available based on the conftest version they're using. Right now, it seems I have to look through the change log for the releases to figure this out.

**Comment by jalseth** [comment]
This is a good idea, I'll look into implementing this. We may need to open a PR to the upstream OPA repo if they don't expose a function for this already.
