### ISSUE TITLE
Request for ppc64le binaries

### ISSUE THREAD

**Issue by seth-priya** [open-policy-agent/conftest#675]
Hi,

I needed ppc64le binaries for conftest as part of an effort to port https://github.com/aquasecurity/starboard. I do see binaries for x86 and arm64 at https://github.com/open-policy-agent/conftest/releases/tag/v0.30.0 currently but not for ppc64le!

I tried to build top-of-tree source code and the build, unit and acceptance tests all pass without any issues on ppc64le.

So, looks like adding ppc64le after 
https://github.com/open-policy-agent/conftest/blob/master/.goreleaser.yml#L15
maybe the only change that would be needed?

So, was wondering if it is something that I can request for? 

Thanks in advance!!

**Comment by seth-priya** [comment]
Acceptance test results for reference
`[root@aa1a690be384` conftest]# make test-acceptance
 ✓ Can install plugin from directory
 ✓ Can install plugin from URL

2 tests, 0 failures

 ✓ Policy with multiple failures returns a postive number of failures

1 test, 0 failures

 ✓ Can parse multi-type files

1 test, 0 failures

 ✓ Can parse nested files with name overlap (first)
 ✓ Can parse nested files with name overlap (second)
 ✓ Can have multiple namespace flags

3 tests, 0 failures

 ✓ Can have multiple policy flags

1 test, 0 `failures`

**Comment by jalseth** [comment]
Merged. Thanks for taking the initiative on the PR!

**Comment by seth-priya** [comment]
thanks @jalseth !  just a quick question - for when is the next release tentative planned?

**Comment by jalseth** [comment]
Hi @seth-priya sorry it has taken so long, but we have just made a release and the binaries for this arch are included!

**Comment by seth-priya** [comment]
No problem @jalseth  and thanks for your support, appreciate it!
