### ISSUE TITLE
Allow user to limit capabilities

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/conftest#690]
Like discussed [here](https://github.com/open-policy-agent/community/discussions/155), and later [blogged](https://www.liam-galvin.co.uk/posts/malicious-rego/) about by @liamg, it would be good if there was an option to "harden" conftest similar to what the [capabilities](https://www.openpolicyagent.org/docs/latest/deployments/#capabilities) feature allows for OPA. While there's a bunch of "ifs" that would need to align for this to be a feasible attack vector, it would be good to at least have the option to prevent it if desirable.

The plumbing is in OPA already, so we'd get a lot for free by tapping into that, but I'm definitely open to alternative approaches as well.

**Comment by jalseth** [comment]
Sounds like a solid improvement! As always, we'd welcome a PR.

**Comment by anderseknert** [comment]
@boranx indeed - it should be pretty straightforward.

**Comment by boranx** [comment]
I'd love to work on this, if there's no taker, I can pick it up and propose a PR

**Comment by anderseknert** [comment]
Awesome! Go right ahead @boranx 👍
