### ISSUE TITLE
Release 0.30.0 not present anymore

### ISSUE THREAD

**Issue by edbighead** [open-policy-agent/conftest#700]
Can't find it anymore, although tag is there.
```bash
$ wget --quiet -O - "https://api.github.com/repos/open-policy-agent/conftest/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | cut -c 2-
0.29.0
```

Tools that were using it can not be built anymore 😞 
https://github.com/runatlantis/atlantis/blob/c43c0437ff355804c2a98cda38e21e27e0b7e5ea/Dockerfile#L37-L55

**Comment by jalseth** [comment]
Hi, thank you for raising this to our attention. I'm not sure why this is, we are looking into it.

**Comment by jalseth** [comment]
v0.30.0 has been re-released at the same commit and tag, but the binaries and checksums are different due to having to be rebuilt. Please let me know if there's anything else you need us to do. We can also release v0.30.1 at the same commit if needed.

**Comment by nairb774** [comment]
A new release would be much appreciated. The hash changes for the released artifacts broke a number of things that we have which expect the hashes to never change for a release. A new release would at least make it a little easier to put things back together.

**Comment by anderseknert** [comment]
Have checked the event logs, but unfortunately GitHub does not seem to emit any events releated to releases. So there's really no way that I'm aware of to say for sure what happened here :/

**Comment by jalseth** [comment]
@nairb774 I've tagged `v0.30.1` at the same commit and it has been released. There are no code changes from v0.30.0.

**Comment by jalseth** [comment]
@anderseknert Thanks for looking into it. For now, I think we've done all we can. Apologies to everyone this impacted.

**Comment by chenrui333** [comment]
Thanks @jalseth !

**Comment by nairb774** [comment]
Thank you!
