### ISSUE TITLE
`conftest push` creates new images even without changes

### ISSUE THREAD

**Issue by jalseth** [open-policy-agent/conftest#705]
Each run of `conftest push` creates a new image with a new SHA256 even if the policies included are the exact same. The images should be the same if the policies do not change. Need to investigate why this is happening and fix.

For example:

```
$ conftest push -p examples/kubernetes/policy us-west1-docker.pkg.dev/test-gar-348023/conftest01/foo:v1
2022/04/26 20:21:40 pushing bundle to: us-west1-docker.pkg.dev/test-gar-348023/conftest01/foo:v1
2022/04/26 20:21:41 pushed bundle with digest: sha256:756dd78cadcfee3c9df973974e31fa05f26a0aa6ea8e0866db99d7368c89e04d

$ conftest push -p examples/kubernetes/policy us-west1-docker.pkg.dev/test-gar-348023/conftest01/foo:v1
2022/04/26 20:21:46 pushing bundle to: us-west1-docker.pkg.dev/test-gar-348023/conftest01/foo:v1
2022/04/26 20:21:47 pushed bundle with digest: sha256:d17a8fe37ff935a07f106e9c6d31381d33d1269135565f698f0c04c52de2d999

$ conftest push -p examples/kubernetes/policy us-west1-docker.pkg.dev/test-gar-348023/conftest01/foo:v1
2022/04/26 20:21:52 pushing bundle to: us-west1-docker.pkg.dev/test-gar-348023/conftest01/foo:v1
2022/04/26 20:21:53 pushed bundle with digest: sha256:150733ed8cec552931cd29a240a589d7ce11ca4a1fe96ad0929feca9aa18b2d3
```

<img width="662" alt="Screen Shot 2022-04-26 at 20 23 03" src="https://user-images.githubusercontent.com/34321259/165433630-ba1ef5bf-53a3-46f6-9b04-647db07489ac.png">

**Comment by boranx** [comment]
is there a possibility that https://github.com/open-policy-agent/conftest/pull/702 solved the problem?
I got the same thing when testing with version: _Conftest: v0.31.0-1-g127a_ but worked well with the latest commit

**Comment by jpreese** [comment]
Seems probable as thats what we use for communicating with registries

**Comment by jalseth** [comment]
Confirmed, this seems to be resolved in the latest commit.
