### ISSUE TITLE
Publishing to gitlab container registry fails with v0.32.0 but succeeds with v0.31.0

### ISSUE THREAD

**Issue by tspearconquest** [open-policy-agent/conftest#717]
Hi,

We have a strange situation with conftest v0.32.0.

We publish our policies to the gitlab container registry using Gitlab CI pipelines, and when the `conftest publish` takes place, if there are no changes to the image, the response from gitlab is successful, and the policies are published.

However, even making a very simple change, such as adding a letter to a double quoted string in a rule, and then having the pipeline try to publish that change, results in a 400 bad request response from Gitlab.

We have opened a ticket with Gitlab Support and are working with them to troubleshoot if this is a Gitlab issue or conftest issue.

I should note here that conftest v0.31.0 successfully publishes in all of our tests without fail, so for the moment we are considering rolling back to v0.31.0.

**Comment by tspearconquest** [comment]
Hello, we have rolled back to v0.31.0 as we are not getting any failures using that version.

Can you please help us communicate to Gitlab what changes were made in v0.32.0 which may have broken publishing? The only requirements to break publishing are as follows:

* Be publishing from a CI pipeline in Gitlab
* Be publishing to the Gitlab container registry
* Be running conftest v0.32.0 or higher
* ** Make any change to the policy**
  * This is important. If you are re-publishing the same policy (regardless of whether you are publishing a new tag in the container registry or a pre-existing tag), then the publish completes properly, but if you make any change and then publish (again, regardless of whether you change the tag in the container registry or not), then the publish fails with a 400.

**Comment by jalseth** [comment]
Hi, I was able to replicate this issue on Google Cloud Artifact Registry, so it is not specific to GitLab. It succeeds if pushing an OCI image that already exists in the remote registry, but fails if it is a new image.

**Comment by tspearconquest** [comment]
Based on Gitlab's comments, and the fact that it was replicated on Google Cloud, this seems to be a bug in the new release.

**Comment by xarses** [comment]
Sounds like the same problem in #716, You can push existing artifacts, but new artifacts wont upload

**Comment by tspearconquest** [comment]
This is the same, yes. Closing this in favor of it.
