### ISSUE TITLE
Deny by map value 

### ISSUE THREAD

**Issue by jlepere-everlaw** [open-policy-agent/conftest#725]
Is it possible to write a single `deny` statement to test that a map has a particular value for a given key? For example:

```
deny[msg] {
    input.foo == "bar"
    msg := "Value at key \"foo\" is not \"bar\"."
}
```

A test with `input` as `{}` is *not* denied.

Is there another way to get around this other than writing two test, one for testing that the key exists and another that the value is correct?

**Comment by jalseth** [comment]
You need to use the `not` keyword.

```rego
package main

deny[msg] {
    not input.foo == "bar"
    msg := "Value at key \"foo\" is not \"bar\"."
}
```

A more flexible alternative is writing a rule with multiple conditions that satisfy it. You can write any number of conditions this way and they are ORed together.

```rego
package main

deny[msg] {
    foo_must_be_bar
    msg := "Value at key \"foo\" is not \"bar\"."
}

foo_must_be_bar {
  input.foo != "bar"
}

foo_must_be_bar {
  not input.foo
}
```

Please not that this tracker is for issues related to conftest and is not a general support channel for writing Rego. The best place to find assistance in those cases is the `#help` channel on the OPA Slack.

**Comment by jlepere-everlaw** [comment]
Thank you, @jalseth, for the solution and the best practices tip.
