### ISSUE TITLE
Netlify: select a new build image

### ISSUE THREAD

**Issue by nate-double-u** [open-policy-agent/conftest#742]
Notice from Netlify
> After November 15, 2022, builds for this site will fail unless you [update the build image](https://app.netlify.com/sites/cloudevents-io/settings/deploys#build-image-selection).

As reported via deploy logs:
> DEPRECATION NOTICE: Builds using the Xenial build image will fail after November 15th, 2022.
> 
> The build image for this site uses Ubuntu 16.04 Xenial Xerus, which is no longer supported.
All Netlify builds using the Xenial build image will begin failing in the week of November 15th, 2022.
>
> To avoid service disruption, please select a newer build image at the following link:
https://app.netlify.com/sites/etcd/settings/deploys#build-image-selection
>
> For more details, visit the build image migration guide:
> https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239

**Comment by boranx** [comment]
the new builds fail due to this: https://app.netlify.com/sites/vibrant-villani-65041c/deploys/637ce049158134000841a2a9

```shell
  UNSUPPORTED BUILD IMAGE

  The build image for this site uses Ubuntu 16.04 Xenial Xerus, which is no longer supported.

  To enable builds for this site, select a later build image at the following link:
  https://app.netlify.com/sites/vibrant-villani-65041c/settings/deploys#build-image-selection
```
@jpreese @garethr @jalseth could you help fix the build image to the latest? (I'd be happy to take care of that but probably I don't have perms on the account `boran.seref@gmail.com` in netlify )

**Comment by jpreese** [comment]
Doesn't look like I have permission to manage Netlify either. My guess would be @garethahealy as he set it all up originally.

**Comment by nate-double-u** [comment]
I can add folks, please send me a list of emails in the CNCF Slack (or here if you don't mind them being public)

**Comment by jpreese** [comment]
Oh wow, awesome. john@reese.dev 

Thanks 🎉

**Comment by nate-double-u** [comment]
I've sent collaborator invites out. I think this should give you access to change the build image, if not please let me know.

**Comment by nate-double-u** [comment]
Would you also be able to manage https://github.com/openebs/website/issues/335?

**Comment by jpreese** [comment]
@nate-double-u I'm not quite sure I understand. Netlify for `conftest` is managed here: https://app.netlify.com/sites/vibrant-villani-65041c/deploys and not under OpenEBS. I may be missing what you're trying to accomplish.

**Comment by nate-double-u** [comment]
ack, sorry, been doing a few of these today. Made a mistake in the invite, let me correct.

**Comment by nate-double-u** [comment]
_correct_ invite sent @jpreese, still collaborator, please let me know if that permission level is appropriate.

**Comment by jpreese** [comment]
Lifesaver, @nate-double-u! Worked.

I updated the build image to be `Ubuntu Focal 20.04 (default)`

**Comment by nate-double-u** [comment]
Awesome!

Closing as updated. Thanks @jpreese!

**Comment by boranx** [comment]
@nate-double-u was there a time-threshold for the invite? I got the email but if I hit it, I got `Failed to accept invite:
Not Found`
