### ISSUE TITLE
Conftest ignores NO_PROXY environment variable in v0.37

### ISSUE THREAD

**Issue by theiltho** [open-policy-agent/conftest#763]
`conftest pull` doesn't work anymore in environments with a corporate proxy. With v0.37.0 the environment variable `NO_PROXY` is ignored:

```
$ export HTTPS_PROXY=<proxy-address>
$ export NO_PROXY=<my-policy-url>

$ conftest pull <my-policy-url>
Error: download policies: client get: error downloading 'https://<my-policy-url>': /usr/bin/git exited with 128: Cloning into '/tmp/922378/temp'...
fatal: unable to access 'https://<my-policy-url>': Received HTTP code 502 from proxy after CONNECT
```

A rollback to v0.36.0 solves this issue.

**Comment by boranx** [comment]
thanks for reporting this, I dug into `pull` a bit, and apparently it performs all get operations using go-getter
However, I couldn't see any recent change on that lib

```shell
git diff v0.36.0 v0.37.0 | grep github.com/hashicorp/go-getter
```
Could there be an issue with how the no-proxy is defined? For instance, defining the url without https and relevant suffixes worked on my local:

```shell
export HTTPS_PROXY=https://dummyproxy
export NO_PROXY=github.com
./conftest pull https://github.com/my-repo/opa-lab.git
```

Also, v0.36.0 worked as 0.37.0 or I couldn't reproduce the issue at all

**Comment by theiltho** [comment]
> Also, v0.36.0 worked as 0.37.0 or I couldn't reproduce the issue at all

I think this is how you should be able to reproduce it, at least this is what happens in my setup:

```
$ docker run -e "HTTPS_PROXY=http://proxy.example.com:8080" -e "NO_PROXY=example.com" openpolicyagent/conftest:v0.36.0 pull "git::https://git.example.com/opa-lab.git/conftest?ref=mybranch"
$ # no output, good thing

$ docker run -e "HTTPS_PROXY=http://proxy.example.com:8080" -e "NO_PROXY=example.com" openpolicyagent/conftest:v0.37.0 pull "git::https://git.example.com/opa-lab.git/conftest?ref=mybranch"
Error: download policies: client get: error downloading 'https://git.example.com/opa-lab.git/conftest?ref=mybranch': /usr/bin/git exited with 128: Cloning into '/tmp/getter4200672575/temp'...
fatal: unable to access 'https://git.example.com/opa-lab.git/': Received HTTP code 502 from proxy after CONNECT
```
Looks like there is an issue with the container; testing locally I can't reproduce it either. Unfortunately we use the docker container within our CI/CD pipelines, that's probably why the rollback to 0.36.0 worked for us.

**Comment by jalseth** [comment]
@theiltho I am not able to reproduce the issue with v0.36, v0.37, or v0.38.

```
$ docker run -e "HTTPS_PROXY=http://proxy.example.com:8080" -e "NO_PROXY=github.com" openpolicyagent/conftest:v0.36.0 pull "git::https://github.com/open-policy-agent/conftest.git?ref=master"

$ echo $?
0

$ docker run -e "HTTPS_PROXY=http://proxy.example.com:8080" -e "NO_PROXY=github.com" openpolicyagent/conftest:v0.37.0 pull "git::https://github.com/open-policy-agent/conftest.git?ref=master"

$ echo $?
0

$ docker run -e "HTTPS_PROXY=http://proxy.example.com:8080" -e "NO_PROXY=github.com" openpolicyagent/conftest:v0.38.0 pull "git::https://github.com/open-policy-agent/conftest.git?ref=master"

$ echo $?
0
```

**Comment by theiltho** [comment]
Ok, v0.38 und v0.39 are working for me, too. Only v0.37 seems to be problematic. I'll close this issue since the latest versions are working. Thank you for your time guys 👍🏼
