### ISSUE TITLE
Option to filter out `SUCCESS` policy evaluation results

### ISSUE THREAD

**Issue by wtait1-ff** [open-policy-agent/conftest#769]
My team is increasingly leveraging `conftest` to improve the SDLC for our Helm charts + Kustomize apps. The experience has been great so far 🎉  but as we continue to test more of our apps and especially as we author more policies, the amount of log output is becoming hard to dig through. (note: all our IaC is in a monorepo and so we have a single test entrypoint for local development + CI that prints all `conftest` output for all our k8s apps).

The same is true when trying to debug further via `--trace`. The output is useful, but I have to scroll until I find the 1 input file that's colored red to get to the trace output I want 😞 

So looking at the current flags for `conftest test`, I see there's already a flag `--suppress-exceptions` so perhaps a `--suppress-successes` would be a quick win? In my head, ideally there would be something like a `--include <listof fail,warn,exception,success>` (and maybe an analogous `--exclude <...>` as well). Not sure what the roadmap for `conftest` looks like though as far as deprecating old flags (`--surpress-exceptions` if the newer `--include` approach was taken up).

---

also just a P.S. to the maintainers but it would be a small but nice addition to write an [`ISSUE_TEMPLATE.md`](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository) for the repo.

In lieu of one, here's some info about my local env

```sh
❯ conftest -v
Conftest: 0.37.0
OPA: 0.47.3
```

**Comment by jpreese** [comment]
As a feature, I think this makes sense. We already have `--quiet` as part of the `verify` command, so it may need to be added to `test` as well.

However, as you mentioned, it may be valuable to allow users to be able to specify what they want to see. Thinking aloud `--quiet` could be used to show everything except errors, keeping the behavior we have today -- and add a more "choose your own adventure" command like the ones you have above.

If that makes sense, we should be able to add `--quiet` without much trouble, and punt the new flag down the road until a concrete case for it comes up.

cc @jalseth for thoughts

**Comment by wtait1-ff** [comment]
I hadn't even noticed the `conftest verify --quiet` flag yet - that sounds perfect for a short-term enhancement

**Comment by jalseth** [comment]
Both options seem reasonable to me and should be straightforward to implement.
