### ISSUE TITLE
enable strict compilation rules in policies

### ISSUE THREAD

**Issue by boranx** [open-policy-agent/conftest#776]
hey team

There's a nice tweak https://www.openpolicyagent.org/docs/latest/strict/ that allows the user to impose strict compilation rules in a given policy such as checking unused variables or unused imports. I think this might be synced down to conftest too so the users would have a similar experience compared to opa
I think the implementation of it would be pretty straight-forward because it's already an option for `NewCompiler()` if it is tainted with `WithStrict(true)` and could be manageable thru a flag

Looking forward to hearing your thoughts on that, thanks all in advance

**Comment by jalseth** [comment]
Seems like a good idea to me. I'd be open to a PR if you have the time.

**Comment by boranx** [comment]
ack, I'll propose a PR if I find some cycles
