### ISSUE TITLE
conftest verify example fails

### ISSUE THREAD

**Issue by pkordes** [open-policy-agent/conftest#781]
Any test that I write with a `not deny` automatically fails.  I have verified this with the deny.rego and deny_test.rego as shown on the main conftest.dev page.  I expect that all 3 tests should pass when running `conftest verify` but only the first one passes.  What is wrong here?  I am copy/pasting the file contents from the main page here:

**deny.rego**

deny[msg] {
  proto := input.resource.aws_alb_listener[lb].protocol
  proto == "HTTP"
  msg = sprintf("ALB `%v` is using HTTP rather than HTTPS", [lb])
}

**deny_test.rego**

test_deny_alb_http {
  cfg := parse_config("hcl2", `
    resource "aws_alb_listener" "lb_with_http" {
      protocol = "HTTP"
    }
  `)
  deny with input as cfg
}

test_deny_alb_https {
  cfg := parse_config("hcl2", `
    resource "aws_alb_listener" "lb_with_https" {
      protocol = "HTTPS"
    }
  `)
  not deny with input as cfg
}

test_deny_alb_protocol_unspecified {
  cfg := parse_config("hcl2", `
    resource "aws_alb_listener" "lb_with_unspecified_protocol" {
      foo = "bar"
    }
  `)
  not deny with input as cfg
}

**Comment by pkordes** [comment]
> conftest -v
Conftest: 0.39.0
OPA: 0.49.0

> conftest verify
FAIL - policy/deny_test.rego -  - data.main.test_deny_alb_https
FAIL - policy/deny_test.rego -  - data.main.test_deny_alb_protocol_unspecified

3 tests, 1 passed, 0 warnings, 2 failures, 0 exceptions, 0 skipped

**Comment by pkordes** [comment]
So the documentation as written on the current page (which is the example I tried) is wrong?Sent from my iPhoneOn Feb 22, 2023, at 6:01 PM, John Reese ***@***.***> wrote:﻿
deny is defined in your ruleset so it will always exist, but it may not contain errors. A deny exists, when one or more entries are added to deny.
i.e. you'd write your assertion like:
test_deny_alb_protocol_unspecified {
  cfg := parse_config("hcl2", resource "aws_alb_listener" "lb_with_unspecified_protocol" { foo = "bar" })
  count(deny) == 0 with input as cfg
}
or
test_deny_alb_protocol_unspecified {
  cfg := parse_config("hcl2", `
    resource "aws_alb_listener" "lb_with_unspecified_protocol" {
      foo = "bar"
    }
  `)
  not deny["ALB lb_with_http is using HTTP rather than HTTPS"] with input as cfg
}

**Comment by jpreese** [comment]
It would appear so, yes.

**Comment by jpreese** [comment]
This has been resolved in #801
