### ISSUE TITLE
Support multi arch docker build

### ISSUE THREAD

**Issue by vtorikianupgrade** [open-policy-agent/conftest#790]
It would be a good thing to support multi arch docker builds (linux/amd64 and linux/arm64 are the obvious ones)

TODO:

- Update docker build calls
- Update extenal dependencies to versions that supports arm64
  - terraform cli (earliest versions that supports arm64 is [v0.12.31](https://releases.hashicorp.com/terraform/0.12.31/)
  - kustomize cli (earliest versions that supports arm64 is [v4.0.0](https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv4.0.0)

**Comment by jalseth** [comment]
Fixed via #789
