### ISSUE TITLE
Update hashicorp/go-getter to 1.7.1

### ISSUE THREAD

**Issue by jpreese** [open-policy-agent/conftest#813]
Dependabot flagged `hashicorp/go-getter` with the following: https://github.com/open-policy-agent/conftest/security/dependabot/25

We are currently onl `1.6.1`: https://github.com/open-policy-agent/conftest/blob/master/go.mod#L16

**Comment by akarshit49** [comment]
Hi @jpreese , can I work on this issue? I am a new open source contributor.

**Comment by jpreese** [comment]
Of course! Let me know if you have any questions.
