### ISSUE TITLE
Update examples documentation to match current examples

### ISSUE THREAD

**Issue by jpreese** [open-policy-agent/conftest#814]
On our documentation page, we link to examples that showcase how to use the different parsers we have available: https://www.conftest.dev/examples/

These link to examples that are found in the repository: https://github.com/open-policy-agent/conftest/tree/master/examples

This examples that are in the GitHub repository are the source of truth, and the documentation page should link to them. However, the documentation page has grown stale.

**Comment by Parsifal-M** [comment]
Hey 👋 

Ignore the linked commit to this I referenced the wrong ticket 🥲
