### ISSUE TITLE
conftest plugin install fails

### ISSUE THREAD

**Issue by pankajmt** [open-policy-agent/conftest#820]
What am I doing wrong here? I am using brew installed conftest on MacOS Ventura!

Attempting GIT URL times out
```
conftest plugin install git://github.com/open-policy-agent/conftest//contrib/plugins/kubectl
Error: install: install from url: download plugin: client get: error downloading 'git://github.com/open-policy-agent/conftest': /usr/bin/git exited with 128: Cloning into '/var/folders/t6/gd_5d05j27q0dghlwf9kndtw0000gn/T/getter2418358981/temp'...
fatal: unable to connect to github.com:
github.com[0: 20.248.137.48]: errno=Operation timed out
```

Attempting HTTPs versions gives errors

```
conftest plugin install https://github.com/open-policy-agent/conftest//contrib/plugins/kubectl
Error: install: install from url: loading plugin from dir: read config: open /Users/ptolani/.conftest/plugins/conftest-plugin-657076014/plugin.yaml: no such file or directory
```
```
conftest plugin install https://github.com/open-policy-agent/conftest/tree/master/contrib/plugins/kubectl
Error: install: install from url: loading plugin from dir: read config: open /Users/ptolani/.conftest/plugins/conftest-plugin-173386885/plugin.yaml: no such file or directory
```

**Comment by boranx** [comment]
Hey @pankajmt 

I've just gone over the readme of the plugin and go-getter, I think the following should do the trick (removing the `git` header and one of the double-slash)

```shell
./conftest plugin install github.com/open-policy-agent/conftest/contrib/plugins/kubectl

ll ~/.conftest/plugins/kubectl
total 8
drwxr-xr-x 4 bseref staff  128 Apr 30 16:15 ./
drwxr-xr-x 3 bseref staff   96 Apr 30 16:15 ../
-rwxr-xr-x 1 bseref staff 1876 Apr 30 16:15 kubectl-conftest.sh*
-rw-r--r-- 1 bseref staff  368 Apr 30 16:15 plugin.yaml

```

**Comment by pankajmt** [comment]
Hey @boranx
 
Many thanks. That worked. Looks like the main conftest plugins page needs updating. 

![image](https://user-images.githubusercontent.com/32150474/235380694-b2fdd543-58e4-4652-a7be-cb902c9824cc.png)

**Comment by pankajmt** [comment]
https://github.com/open-policy-agent/conftest/pull/822 - the least i could do

**Comment by boranx** [comment]
yeah, as far as I know, for the download-upload operations conftest relies on `go-getter`, and sometimes there might be small ui/ux changes when the version of it's bumped-up
Feel free to propose more if there are places that need to be updated, all PRs are welcome

**Comment by boranx** [comment]
For posterity, the plugin install functionality is also protected by e2e tests: https://github.com/open-policy-agent/conftest/blob/master/tests/plugin/test.bats#L10
