### ISSUE TITLE
Bump-up go version to 1.20

### ISSUE THREAD

**Issue by boranx** [open-policy-agent/conftest#837]
This is to bump up to the latest Go version in the maintenance context. It should be straightforward/safe given there are no breaking changes for Conftest that need to be applied since 1.19

e.g:
```shell
go mod edit -go 1.20
make build
make test
make test-acceptance
make test-examples
```

**Comment by jalseth** [comment]
@boranx I don't think we want to do this just yet. When the version in `go.mod` is increased, all previous versions of Go cannot build the package. Go v1.19 is officially supported until 1 year after release (2023-08-03). After this date, we can bump the version.

**Comment by boranx** [comment]
ack, sounds good! Do we have a label specifying the change that needs to be done after a target date, or would it be better/more elegant closing the issue and re-open it when the maintenance window comes?

**Comment by jalseth** [comment]
@boranx I don't think we have any such labels. This change can be made now, 1.19 is no longer supported.

**Comment by jalseth** [comment]
Resolved in https://github.com/open-policy-agent/conftest/pull/927 because it was blocking CI.
