### ISSUE TITLE
OPA and Conftest CLI does not provide same result

### ISSUE THREAD

**Issue by AlexanderRasmussen** [open-policy-agent/conftest#840]
We have recently update to the newest version of Conftest and starting seeing an issue. We have managed to figure that the issue was introduced in conftest version 0.42

We have the following rego:
``` rego
change_actions := ["create", "update", "no-op"]

reference_kms_by_arn(resource) {
    keyId := resource.change.after.kms_key_id      
    startswith(keyId, "arn:aws:kms:")
}

deny[reason] {
    some resource in input.resource_changes
    resource.mode == "managed"
    action := resource.change.actions[count(resource.change.actions) - 1]
    action in change_actions
    resource.type == "aws_cloudwatch_log_group"

    not reference_kms_by_arn(resource)

    reason := sprintf("You have to use CMK (make sure 'kms_key_id' argument is set) - %s", [resource.address])
}
```

The following test of the rego:
``` rego
test_key_null {
	result = m1.deny with input as data.aws.cloudwatch.unittest.m1.invalid.key_null
	count(result) == 1
	result["You have to use CMK (make sure 'kms_key_id' argument is set) - aws_cloudwatch_log_group.opa_log_group"]
}
```

The test input:
```json
{
  "m1": {
    "invalid": {
      "key_null": {
        "resource_changes": [
          {
            "address": "aws_cloudwatch_log_group.opa_log_group",
            "mode": "managed",
            "type": "aws_cloudwatch_log_group",
            "name": "opa_log_group",
            "provider_name": "registry.terraform.io/hashicorp/aws",
            "change": {
              "actions": [
                "create"
              ],
              "after": {
                "kms_key_id": null
              }
            }
          }
        ]
      }
    }
  }
}
```

With these three input files running OPA test it passes succesfully while, running conftest version 0.42 and above with the same policies gives us the following error:
`Error: running test: query rule: check: query rule: built-in error: [{eval_type_error startswith: operand 1 must be string but got null policy\aws\cloudwatch\m1.rego:15}]`

While it succeeds with Conftest version 0.41

We know that the fix is to add a null check before the startswith - but it is rather frustrating to do this +100 places and not being sure if we have missed it somewhere 😄

**Comment by boranx** [comment]
Hey @AlexanderRasmussen 

Thanks for reporting the issue. I believe this could start to happen as of https://github.com/open-policy-agent/conftest/pull/812 where we put a check whether the built-in function provided by opa returns an error
This was to catch unintended failures by built-in functions and to prevent the errors from being devoured
You can see the same behavior in OPA subcommands with `--show-builtin-errors` or `--strict-builtin-errors`
To provide a similar UI/UX to opa, maybe it'd be worth introducing similar flags in conftest
Nevertheless, I'd say fixing the built-in errors in the policy files might be more elegant
cc: @jpreese @jalseth for feedback & thoughts
