### ISSUE TITLE
Add support for adding built-in functions

### ISSUE THREAD

**Issue by lcarva** [open-policy-agent/conftest#856]
Hello!

I'm one of the maintainers of the [Enterprise Contract CLI](https://github.com/enterprise-contract/ec-cli). We use the [conftest runner](https://github.com/enterprise-contract/ec-cli/blob/27b9e7fe52698bfcd264f943a3deaa4c1e0b21bc/internal/evaluator/conftest_evaluator.go#L143C5-L148) to evaluate rego policies. This is more beneficial to us than using opa directly. 

We have certain requirements that could be met by using custom [built-in functions](https://www.openpolicyagent.org/docs/latest/extensions/).

Would you be open to extending the TestRunner API to support this? If so, I'm happy to provide a patch!

**Comment by jalseth** [comment]
If you are using conftest as a library, I don't think you need to modify conftest to add new builtins. The builtins are globally namespaced. You can register builtins using [`rego.RegiserBuiltin{1..4}`](https://pkg.go.dev/github.com/open-policy-agent/opa/rego#RegisterBuiltin1) which will be used by the conftest runner. You can see some examples of builtins Conftest adds to the OPA engine in https://github.com/open-policy-agent/conftest/blob/master/builtins/parse_config.go.

**Comment by lcarva** [comment]
@jalseth, thanks! I wasn't aware of that. I have just verified that it works as expected.
