### ISSUE TITLE
OPA doesn't consider built-in error fatal, but Conftest does. Can we revert the change?

### ISSUE THREAD

**Issue by ruokai-lai** [open-policy-agent/conftest#870]
**Request:**
OPA doesn't consider built-in error fatal, but Conftest does. Can we revert the change? Or make it print out builtin errors as opa with flag  `--show-builtin-errors`. 

**In OPA, where it shows "built in errors are not fatal":**
Run `opa eval --help`:  you can see `--show-builtin-errors  collect and return all encountered built-in errors, built in errors are not fatal`.

**In Conftest, where it shows conftest fails with built in error:**
introduced in version `0.42` https://github.com/open-policy-agent/conftest/blob/master/policy/engine.go#L449
```
if len(*builtInErrors) > 0 {
		return output.QueryResult{}, fmt.Errorf("built-in error: %s", (*builtInErrors))
}
```
Example of failure:
this will fail my conftest: https://play.openpolicyagent.org/p/wyU6iLcazl
and this will not fail my conftest: https://play.openpolicyagent.org/p/uk0FOQyNsO

**Comment by boranx** [comment]
I think it's fair to expect to have a similar user experience to OPA for builtin errors
to address that, I've moved the builtin errors behind a flag (--show-builtin-errors) in the PR: #781
