### ISSUE TITLE
Has anyone used conftest in s390x environment?

### ISSUE THREAD

**Issue by harpaldhillon** [open-policy-agent/conftest#888]
Hi All,

I've a requirement to run conftest compliance tests in s390x based machine. I'm able to generate the s390x package by adding GOARCH flag when building the package. But I'm still waiting for the s390x machine to be provisioned before I can test the conftest binary.

```
root@afd70aee0d65:~/conftest# file conftest 
conftest: ELF 64-bit MSB executable, IBM S/390, version 1 (SYSV), statically linked, Go BuildID=Kw21OPDg4wPNzxa8JFiO/X-E5FPNdpcXyTYuoO7Oi/9fJwBbAutZSlp_y9IVQm/OT9-6gS19eAo7Et5n9Tz, with debug_info, not stripped
```

Anyone else used conftest in s390x based environment? Any challenges or issues they faced?

Thanks and Regards,
Harpal Dhillon

**Comment by jalseth** [comment]
No reason it wouldn't work, conftest doesn't rely on any Cgo and Go supports `s390x` as you've discovered. If you'd like this architecture to be included for builds in the official conftest releases, feel free to open a PR to update the config: https://github.com/open-policy-agent/conftest/blob/7f56296f3296a16d73553f9d510b435a1c15e73a/.goreleaser.yml#L13

**Comment by jalseth** [comment]
Added in https://github.com/open-policy-agent/conftest/pull/905
