### ISSUE TITLE
Improper if Usage seems to miss a valid case

### ISSUE THREAD

**Issue by chriskuchin** [open-policy-agent/conftest#934]
So this [MR](https://github.com/open-policy-agent/conftest/pull/902/files) made a change it v0.49.0 to flag bad usages of the if keyword. 

However I use conftest in my terraform pipelines and rolling to v0.49.0 caused my pipelines to all error with

>	* policy_set: regula: conftest: Error: running test: load: loading policies: rule is using 'if' keyword without 'contains' keyword: rule in /opt/policies/regula/rules/tf/aws/security_groups/ingress_11215.rego at line 31

This points to [this rule](https://github.com/fugue/regula/blob/master/rego/rules/tf/aws/security_groups/ingress_11215.rego#L31) in the regula repository. From my understanding this is not a problem but the regex is failing on this case.

Happy to understand where I misunderstand the problem. I have rolled back to v0.48.0 for now.

FYI @boranx & @jalseth

**Comment by jalseth** [comment]
This appears to be a bug with a bare `deny` without the `[msg]` portion which changes the Rego AST representation.
