### ISSUE TITLE
fix: There is a regex issue in downloader

### ISSUE THREAD

**Issue by wangshu3000** [open-policy-agent/conftest#971]
The regex in oci_detector.go is not in correct format.

In regex, the dot . in domain should be escaped. 
For example: `*****.**, should be *****\.**`

So that it'll match the \. as a . string, but not any single character in regex.

I would like to raise a PR to fix it.

**Comment by boranx** [comment]
hi @wangshu3000 

Thanks for reporting the issue, yeah feel free to propose a PR
