### ISSUE TITLE
How can I validate a variable that is a Json ?

### ISSUE THREAD

**Issue by rgleme** [open-policy-agent/conftest#997]
Hello

I would like conftest to validate a variable that is a Json. EG:
plan.json
`{
    "format_version": "1.2",
    "terraform_version": "1.8.0",
    "planned_values": {
        "root_module": {
            "resources": [
                {
                    "address": "aws_sqs_queue.terraform_queue",
                    "mode": "managed",
                    "type": "aws_sqs_queue",
                    "name": "terraform_queue",
                    "provider_name": "registry.terraform.io/hashicorp/aws",
                    "schema_version": 0,
                    "values": {
                        "content_based_deduplication": false,
                        "delay_seconds": 90,
                        "fifo_queue": false,
                        "kms_master_key_id": null,
                        "max_message_size": 2048,
                        "message_retention_seconds": 86400,
                        "name": "terraform-example-queue",
                        "policy": "{\"Id\":\"__default_policy_ID\",\"Statement\":[{\"Action\":\"SQS:*\",\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"*\"},\"Resource\":\"arn:aws:sqs:us-east-1:649991419996:sqstag\",\"Sid\":\"__owner_statement\"}],\"Version\":\"2012-10-17\"}",
                        "receive_wait_time_seconds": 10,
                        "tags": null,
                        "visibility_timeout_seconds": 30
                    },
                    "sensitive_values": {
                        "tags_all": {}
                    }
                }
            ]
        }
    },
    "resource_changes": [
        {
            "address": "aws_sqs_queue.terraform_queue",
            "mode": "managed",
            "type": "aws_sqs_queue",
            "name": "terraform_queue",
            "provider_name": "registry.terraform.io/hashicorp/aws",
            "change": {
                "actions": [
                    "create"
                ],
                "before": null,
                "after": {
                    "content_based_deduplication": false,
                    "delay_seconds": 90,
                    "fifo_queue": false,
                    "kms_master_key_id": null,
                    "max_message_size": 2048,
                    "message_retention_seconds": 86400,
                    "name": "terraform-example-queue",
                    "policy": "{\"Id\":\"__default_policy_ID\",\"Statement\":[{\"Action\":\"SQS:*\",\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"*\"},\"Resource\":\"arn:aws:sqs:us-east-1:1111111111111:sqstag\",\"Sid\":\"__owner_statement\"}],\"Version\":\"2012-10-17\"}",
                    "receive_wait_time_seconds": 10,
                    "tags": null,
                    "visibility_timeout_seconds": 30
                },
                "after_unknown": {
                    "arn": true,
                    "deduplication_scope": true,
                    "fifo_throughput_limit": true,
                    "id": true,
                    "kms_data_key_reuse_period_seconds": true,
                    "name_prefix": true,
                    "redrive_allow_policy": true,
                    "redrive_policy": true,
                    "sqs_managed_sse_enabled": true,
                    "tags_all": true,
                    "url": true
                },
                "before_sensitive": false,
                "after_sensitive": {
                    "tags_all": {}
                }
            }
        }
    ],
    "configuration": {
        "provider_config": {
            "aws": {
                "name": "aws",
                "full_name": "registry.terraform.io/hashicorp/aws"
            }
        },
        "root_module": {
            "resources": [
                {
                    "address": "aws_sqs_queue.terraform_queue",
                    "mode": "managed",
                    "type": "aws_sqs_queue",
                    "name": "terraform_queue",
                    "provider_config_key": "aws",
                    "expressions": {
                        "delay_seconds": {
                            "constant_value": 90
                        },
                        "max_message_size": {
                            "constant_value": 2048
                        },
                        "message_retention_seconds": {
                            "constant_value": 86400
                        },
                        "name": {
                            "constant_value": "terraform-example-queue"
                        },
                        "policy": {
                            "constant_value": "{\n  \"Version\": \"2012-10-17\",\n  \"Id\": \"__default_policy_ID\",\n  \"Statement\": [\n    {\n      \"Sid\": \"__owner_statement\",\n      \"Effect\": \"Allow\",\n      \"Principal\": {\n        \"AWS\": \"*\"\n      },\n      \"Action\": \"SQS:*\",\n      \"Resource\": \"arn:aws:sqs:us-east-1:1111111111111:sqstag\"\n    }\n  ]\n}\n"
                        },
                        "receive_wait_time_seconds": {
                            "constant_value": 10
                        }
                    },
                    "schema_version": 0
                }
            ]
        }
    },
    "timestamp": "2024-09-02T19:54:20Z",
    "applyable": true,
    "complete": true,
    "errored": false
}`

The policy variable contains a Json Structure. I would like Conftest to Deny if "Principal" is equals to "AWS: *"

Is that possible ?

Thank you

**Comment by jalseth** [comment]
OPA has native support for unmarshaling a JSON string https://www.openpolicyagent.org/docs/latest/policy-reference/#builtin-encoding-jsonunmarshal.

**Comment by rgleme** [comment]
Thank you very much 👍
